return { --mason -- NB: this file should be loaded first
	"williamboman/mason.nvim",
	-- event = "VeryLazy",
	opts = {
		ensure_installed = {
			"autoflake",
			"bash-debug-adapter",
			"bash-language-server", -- shell script
			"beautysh",
			"black",
			"cmakelint",
			"checkmake",
			"cspell",
			"cmake_lint",
			"debugpy",
			"rome",
			"pylyzer",
			"debugpy",
			"fixjson",
			"gopls",
			"markdownlint",
			"grammarly-languageserver",
			"shellharden",
			"html-lsp",
			"stylua",
			"json-lsp",
			"jsonlint",
			"lua-language-server",
			"markdown-toc",
			"marksman", -- markdown
			"misspell",
			"proselint",
			"mypy",
			"prettier",
			"pydocstyle",
			"pyright",
			"python-lsp-server",
			"remark-cli",
			"remark-language-server",
			"reorder-python-imports",
			"ruff",
			"rust-analyzer",
			"shellcheck",
			"standardjs",
			"stylelint",
			"stylua",
			"texlab",
			"textlint",
			"tree-sitter-cli",
			"vim-language-server",
			"write-good",
			"yaml-language-server",
			"yamlfix",
			"yamlfmt",
			"yamllint",
			"shellharden",
		},
	},
}
