[completion]
copilot = "custom"
activate_on_typing = true

[display]
cell_output = "above"
dataframes = "rich"
theme = "system"
code_editor_font_size = 14
default_width = "full"

[ai]
rules = ""

[ai.anthropic]

[ai.google]

[runtime]
watcher_on_save = "lazy"
on_cell_change = "autorun"
auto_reload = "off"
std_stream_max_bytes = 1000000
pythonpath = []
auto_instantiate = true
output_max_bytes = 8000000

[package_management]
manager = "uv"

[keymap]
preset = "default"

[keymap.overrides]

[experimental]

[language_servers.pylsp]
enable_pylint = false
enable_pydocstyle = false
enabled = true
enable_flake8 = false
enable_mypy = true
enable_pyflakes = false
enable_ruff = true

[save]
format_on_save = false
autosave = "after_delay"
autosave_delay = 1000

[formatting]
line_length = 79

[snippets]
include_default_snippets = true
custom_paths = []

[server]
browser = "default"
follow_symlink = false
