paths-ignore:
  - "**/*_test.go"
  - "**/*_test.py"
  - "**/*_test.ts"
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.test.js"
  - "**/*_spec.rb"
  - "**/testdata/**"
  - "**/fixtures/**"
  - "**/__fixtures__/**"
