# Python Telegram Bot on NAS
# Self-hosted bot running 24/7 on your NAS
# Ref: https://github.com/CarlosLugones/python-telegram-bot-docker
#
# Crane images needed:
#   crane pull python:3.12-slim /tmp/python-slim.tar
#   (or build custom image, then: docker build + docker save/load)
#
# NAS volume setup:
#   mkdir -p ~/docker/telegram-bot/{app,data}
#   scp bot.py requirements.txt <nas-host>:~/docker/telegram-bot/app/

services:
  telegram-bot:
    build:
      context: /home/<nas-user>/docker/telegram-bot/app
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - /home/<nas-user>/docker/telegram-bot/.env
    volumes:
      - /home/<nas-user>/docker/telegram-bot/data:/app/data

# --- .env file (on NAS: ~/docker/telegram-bot/.env) ---
# TELEGRAM_BOT_TOKEN=your-bot-token-here
# ALLOWED_USERS=123456789,987654321

# --- Dockerfile (on NAS: ~/docker/telegram-bot/app/Dockerfile) ---
# FROM python:3.12-slim
# WORKDIR /app
# COPY requirements.txt .
# RUN pip install --no-cache-dir -r requirements.txt
# COPY . .
# CMD ["python", "bot.py"]

# --- requirements.txt ---
# python-telegram-bot>=21.0

# Build workflow (since NAS can't pull from Docker Hub):
#   1. scp source files to NAS
#   2. crane pull python:3.12-slim /tmp/python-slim.tar
#   3. docker load -i /tmp/python-slim.tar
#   4. docker compose build
#   5. docker compose up -d
