local ls = require("luasnip")
-- some shorthands...
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
	s("24-h", { t("24 hour") }),
	s("inhib.", { t("inhibitor") }),
	s("2G", { t("second generation") }),
	s("2HG", { t("2-hydroxyglutarate") }),
	s("3D", { t("three-dimensional") }),
	s("3G", { t("third generation") }),
	s("4-1BBL", { t("4-1BB ligand") }),
	s("4-PCC", { t("4-factor prothrombin complex concentrate") }),
	s("5-FU", { t("5-fluorouracil") }),
	s("6MP", { t("6-mercaptopurine") }),
	s("9vHPV", { t("9-valent HPV") }),
	s("A/S", { t("HgA and HgS") }),
	s("A2aR", { t("adenosine 2A receptor") }),
	s("AABB", { t("American Association of Blood Banks") }),
	s("ABVD", { t("doxorubicin (A), bleomycin (B), vinblastine (V), dacarbazine (D)") }),
	s("ABW", { t("actual body weight") }),
	s("AC", { t("Doxorubicin (Adriamycin) + cyclophosphamide") }),
	s("AC", { t("anticoagulation") }),
	s("ACC", { t("adrenal cortical carcinoma") }),
	s("ACCP", { t("American College of Chest Physicians") }),
	s("ACOG", { t("American College of Obstetricians and Gynecologists") }),
	s("ACP", { t("advance care planning") }),
	s("ACS", { t("American Cancer Society") }),
	s("ACT", { t("adoptive cell therapy") }),
	s("ACTH", { t("adrenocorticotrophic hormone") }),
	s("AChR", { t("acetylcholine receptor") }),
	s("AD", { t("autosomal dominant") }),
	s("ADC", { t("antibody drug conjugate") }),
	s("ADCC", { t("antibody-dependent cellular cytotoxicity") }),
	s("ADH", { t("antidiuretic hormone") }),
	s("ADL", { t("activities of daily living") }),
	s("ADLS", { t("activities of Daily Living Scale") }),
	s("ADP", { t("adenosine diphosphate"), t("ALAD deficiency porphyria") }),
	s("ADR", { t("adverse drug reaction") }),
	s("AE", { t("adverse event") }),
	s("AED", { t("antiepileptic drugs") }),
	s("AFAP", { t("attenuated familial adenomatous polyposis") }),
	s("AFP", { t("alpha-fetoprotein") }),
	s("AHF", { t("antihemophilic factor") }),
	s("AI", { t("angiogenesis inhibitors") }),
	s("AI", { t("aromatase inhibitor") }),
	s("AICD", { t("antibody-induced cell death") }),
	s("AIHA", { t("autoimmune hemolytic anemia") }),
	s("AIP", { t("acute intermittent porphyria") }),
	s("AIR", { t("autoimmune") }),
	s("AIS", { t("adenocarcinoma in situ") }),
	s("AJ", { t("Ashkenazi Jewish") }),
	s("AJCC", { t("American Joint Committee on Cancer") }),
	s("AKI", { t("acute kidney injury") }),
	s("AL", { t("light chain amyloidosis") }),
	s("ALA", { t("aminolevulinic acid") }),
	s("ALC", { t("absolute lymphocyte count") }),
	s("ALCL", { t("anaplastic large-cell lymphoma") }),
	s("ALD", { t("adrenoleukodystrophy") }),
	s("ALG", { t("anti-lymphocyte globulin") }),
	s("ALK", { t("anaplastic lymphoma kinase") }),
	s("ALK", { t("anaplastic lymphoma kinase") }),
	s("ALL", { t("acute lymphoblastic leukemia") }),
	s("ALND", { t("axillary lymph node dissection") }),
	s("ALP", { t("alkaline phosphatase") }),
	s("ALPS", { t("autoimmune lymphoproliferative syndrome") }),
	s("ALT", { t("alanine aminotransferase") }),
	s("AMKL", { t("acute megakaryoblastic leukemia") }),
	s("AML", { t("acute myeloid leukemia") }),
	s("AMPAR", { t("α-amino-3-hydroxy-5-methyl-4-isoxazolepropionic acid receptor") }),
	s("AMS", { t("altered mental status") }),
	s("ANC", { t("absolute neutrophil count") }),
	s("ANG", { t("angiopoietin") }),
	s("ANG2", { t("angiopoietin 2") }),
	s("ANITA", { t("adjuvant Navelbine International Trialist Association") }),
	s("ANP", { t("atrial natriuretic peptide") }),
	s("AP", { t("anterior posterior"), t("Antiphospholipid"), t("Accelerated phase") }),
	s("APAP", { t("acetaminophen") }),
	s("APCC", { t("anaphase promoting complex/cyclosome") }),
	s("APFAF—1", { t("apoptotic protease activating factor 1") }),
	s("APL", { t("acute promyelocytic leukemia") }),
	s("APR", { t("abdominoperineal resection") }),
	s("APS", { t("antiphospholipid antibody syndrome") }),
	s("AR", { t("autosomal recessive"), t("Androgen receptor") }),
	s("ARA-C", { t("cytarabine") }),
	s("ARA-G", { t("9-beta arabinofuranosylguanine") }),
	s("ARDS", { t("acute respiratory distress syndrome") }),
	s("ARF", { t("acute respiratory failure") }),
	s("ARR", { t("absolute risk reduction") }),
	s("ASA", { t("aspirin") }),
	s("ASCCP", { t("American Society for Colposcopy and Cervical Pathology") }),
	s("ASCT", { t("autologous stem cell transplantation") }),
	s("ASM", { t("aggressive systemic mastocytosis") }),
	s("AST", { t("aspartate aminotransferase") }),
	s("AT", { t("anti-thrombin") }),
	s("ATG", { t("anti-thymocyte globulin") }),
	s("ATLL", { t("adult T-cell leukemia/lymphoma") }),
	s("ATM", { t("ataxia-telangiectasia mutated") }),
	s("ATO", { t("arsenic trioxide") }),
	s("ATP", { t("adenosine triphosphate") }),
	s("ATRA", { t("All-trans retinoic acid") }),
	s("ATRX", { t("Alpha-thalassemia/mental retardation syndrome") }),
	s("AUA", { t("American Urological Association") }),
	s("AUC", { t("area under the curve") }),
	s("AYA", { t("Adolescent and young adult") }),
	s("AZA", { t("Azacytidine") }),
	s("Ab", { t("antibody") }),
	s("AdenoCA", { t("Adenocarcinoma") }),
	s("Allo-HCT", { t("Allogeneic hematopoietic cell transplant") }),
	s("Angio", { t("angiogram") }),
	s("Ant", { t("anterior") }),
	s("Asx", { t("asymptomatic") }),
	s("Aut", { t("autosomal") }),
	s("Auto-HCT", { t("Autologous hematopoietic cell transplant") }),
	s("AutoAb", { t("autoantibody") }),
	s("B-ALL", { t("B-cell acute lymphoblastic leukemia") }),
	s("B-PLL", { t("B prolymphocytic leukemia") }),
	s("B7-H1", { t("B7-homolog 1") }),
	s("B7-H3", { t("B7-homolog 3") }),
	s("BAE", { t("bronchial artery embolisation") }),
	s("BAL", { t("bronchoalveolar lavage") }),
	s("BBB", { t("blood–brain barrier") }),
	s("BBW", { t("Black box warning") }),
	s("BC", { t("blast crisis") }),
	s("BC", { t("breast cancer") }),
	s("BCC", { t("basal cell carcinoma") }),
	s("BCG", { t("Bacillus Calmette-Guérin") }),
	s("BCMA", { t("B-cell maturation antigen") }),
	s("BCNU", { t("carmustine") }),
	s("BCR", { t("B-cell receptor") }),
	s("BCRP", { t("breast cancer resistance protein") }),
	s("BCS", { t("breast conservation surgery") }),
	s("BED", { t("biologically effective dose") }),
	s("BED", { t("biologically equivalent dose") }),
	s("BEP", { t("bleomycin (B), etoposide (E), platinum (P)") }),
	s("BER", { t("base excision repair") }),
	s("BFM", { t("German Berlin, Frankfurt, Muenster Study Group") }),
	s("BH3", { t("Bcl-2 homology domain 3") }),
	s("BID", { t("Twice per day") }),
	s("BK", { t("BK virus") }),
	s("BL", { t("Burkitt lymphoma") }),
	s("BM", { t("bone marrow") }),
	s("BMA", { t("bone marrow aspiration") }),
	s("BMBx", { t("bone marrow biopsy") }),
	s("BMD", { t("bone mineral density") }),
	s("BMF", { t("bone marrow failure") }),
	s("BMI", { t("body mass index") }),
	s("BR", { t("bendamustine (B), rituximab (R)") }),
	s("BRAF", { t("V-raf murine sarcoma viral oncogene homolog B") }),
	s("BRCA", { t("breast cancer gene") }),
	s("BRCA1/2", { t("breast cancer gene 1/2") }),
	s("BRIP1", { t("BRCA1 Interacting Protein 1") }),
	s("BSA", { t("body surface area") }),
	s("BSC", { t("best supportive care") }),
	s("BSO", { t("bilateral salpingo-oophorectomy") }),
	s("BTK", { t("Bruton’s tyrosine kinase") }),
	s("BTKi", { t("Bruton’s tyrosine kinase inhibitor") }),
	s("BTS", { t("British Thoracic Society") }),
	s("BV", { t("brentuximab vedotin") }),
	s("BWS", { t("Beckwith–Weidemann syndrome") }),
	s("Bev", { t("bevacizumab") }),
	s("BiTE", { t("bispecific T-cell engager") }),
	s("Bilat", { t("bilateral") }),
	s("BsAb", { t("bispecific antibody") }),
	s("Bu", { t("busulfan") }),
	s("C'", { t("compliment") }),
	s("C. diff", { t("Clostridium difficile") }),
	s("CA 125", { t("cancer antigen 125") }),
	s("CAD", { t("coronary artery disease") }),
	s("CAI", { t("carboxyaminotriazole") }),
	s("CALGB", { t("Cancer and Leukemia Group B trial group") }),
	s("CAP", { t("Chest, abdomen, pelvis") }),
	s("CAPD", { t("Continuous ambulatory peritoneal dialysis") }),
	s("CAR", { t("Chimeric antigen receptor") }),
	s("CAR-T", { t("Chimeric antigen receptor T-cell") }),
	s("CB", { t("cord blood") }),
	s("CBC", { t("complete blood count") }),
	s("CBE", { t("clinical breast exam") }),
	s("CBF", { t("core binding factor") }),
	s("CBT", { t("cognitive Behaviour Therapy") }),
	s("CBU", { t("cord blood unit") }),
	s("CBV", { t("cyclophosphamide, carmustine, etoposide") }),
	s("CCL2", { t("chemokine (C-C motif) ligand 2") }),
	s("CCND1", { t("cyclin D1") }),
	s("CCNU", { t("lomustine") }),
	s("CCyR", { t("complete cytogenetic response") }),
	s("CD", { t("cluster of differentiation"), t("Collagen disease") }),
	s("CD40L", { t("CD40 ligand") }),
	s("CDA", { t("cladribine"), t("Cytidine deaminase") }),
	s("CDK", { t("cyclin-dependent kinase") }),
	s("CDKN2A", { t("cyclin dependent kinase inhibitor 2A") }),
	s("CEA", { t("carcinoembryonic antigen") }),
	s("CEP", { t("congenital erythropoietic porphyria") }),
	s("CGD", { t("chronic granulomatous disease") }),
	s("CHART", { t("continuous, hyperfractionated, accelerated radiotherapy") }),
	s("CHARTWEL", { t("CHART weekend-less") }),
	s("CHF", { t("congestive heart failure") }),
	s("CHOEP", { t("cyclophosphamide (C), doxorubicin (H), vincristine (O), etoposide (E), prednisone (P)") }),
	s("CHOP", { t("cyclophosphamide (C), doxorubicin (H), vincristine (O), prednisone (P)") }),
	s("CHR", { t("complete hematologic response") }),
	s("CI", { t("confidence intervals") }),
	s("CID", { t("combined immunodeficiency") }),
	s("CIN", { t("cervical intraepithelial neoplasia") }),
	s("CIP", { t("CDK interacting protein") }),
	s("CIS", { t("cisplatin") }),
	s("CISNE", { t("Clinical index of stable febrile neutropenia") }),
	s("CIT", { t("chemoimmunotherapy") }),
	s("CIV", { t("continuous intravenous infusion") }),
	s("CKC", { t("cold knife cone") }),
	s("CLL", { t("chronic lymphocytic leukemia") }),
	s("CLP", { t("common lymphoid progenitors") }),
	s("CML", { t("chronic myeloid leukemia") }),
	s("CMML", { t("chronic myelomonocytic leukemia") }),
	s("CMMRD", { t("constitutional mismatch repair deficiency syndrome") }),
	s("CMP", { t("common myeloid progenitors") }),
	s("CMV", { t("cytomegalovirus") }),
	s("CN", { t("cranial nerves") }),
	s("CN-H", { t("copy number-high") }),
	s("CN-L", { t("copy number-low") }),
	s("CNI", { t("calcineurin inhibitor") }),
	s("CNS", { t("central nervous system") }),
	s("COG", { t("Children’s Oncology Group") }),
	s("COPD", { t("chronic obstructive pulmonary disease") }),
	s("CP", { t("chronic phase") }),
	s("CPI", { t("checkpoint inhibitors") }),
	s("CPK", { t("creatine phosphokinase") }),
	s("CPR", { t("cardio pulmonary resuscitation") }),
	s("CPS", { t("combined positive score") }),
	s("CR", { t("complete response") }),
	s("CR1", { t("first complete remission") }),
	s("CRC", { t("colorectal carcinoma") }),
	s("CRMP", { t("collapsin response mediator protein") }),
	s("CRP", { t("C-reactive protein") }),
	s("CRPC", { t("castrate resistant prostate cancer") }),
	s("CRS", { t("cytokine release syndrome") }),
	s("CRT", { t("chemoradiation") }),
	s("CRT", { t("chemoradiotherapy") }),
	s("CRTC1", { t("CREB regulated transcription coactivator 1") }),
	s("CSA", { t("cyclosporine") }),
	s("CSC", { t("cancer stem cell") }),
	s("CSF", { t("cerebrospinal fluid") }),
	s("CSF-1", { t("colony-stimulating factor 1") }),
	s("CSF1R", { t("colony-stimulating factor 1 receptor") }),
	s("CSI", { t("cranial spinal irradiation") }),
	s("CT scan", { t("computed tomography scan") }),
	s("CT", { t("CT scan") }),
	s("CTCAE", { t("Common Terminology Criteria for Adverse Events") }),
	s("CTL", { t("cytotoxic T-lymphocytes") }),
	s("CTLA-4", { t("cytotoxic T-lymphocyte–associated protein 4") }),
	s("CTLs", { t("cytotoxic T lymphocytes") }),
	s("CTV", { t("clinical target volume") }),
	s("CV", { t("cardiovascular") }),
	s("CVA", { t("cerebrovascular accident") }),
	s("CVC", { t("central venous catheter") }),
	s("CVD", { t("Cardiovascular disease") }),
	s("CVP", { t("cyclophosphamide (C), vincristine (V), prednisone (P)") }),
	s("CVT", { t("cisplatin (C), vinblastine (V), temozolomide (T)") }),
	s("CW", { t("chest wall") }),
	s("CXCL2", { t("chemokine (C-X-C motif) ligand 2") }),
	s("CXR", { t("chest X-ray") }),
	s("CYP", { t("cytochrome") }),
	s("Ca", { t("calcium") }),
	s("Ca", { t("cancer") }),
	s("Carbo", { t("carboplatin") }),
	s("Cat", { t("category") }),
	s("Chr", { t("chromosome") }),
	s("Clo", { t("clofarabine") }),
	s("CoNS", { t("coagulase-negative staphylococci") }),
	s("Cr", { t("creatinine") }),
	s("CrCl", { t("creatinine clearance") }),
	s("Cy", { t("cyclophosphamide") }),
	s("D", { t("day") }),
	s("DAH", { t("diffuse alveolar hemorrhage") }),
	s("DART", { t("dual-affinity retargeting protein") }),
	s("DAT", { t("direct antiglobulin test") }),
	s("DBA", { t("Diamond–Blackfan anemia") }),
	s("DC", { t("dendritic cell") }),
	s("DCIS", { t("ductal carcinoma in situ") }),
	s("DDB2", { t("damaged DNA-binding protein 2") }),
	s("DDI(s)", { t("drug–drug interaction(s)") }),
	s("DDR", { t("DNA damage repair") }),
	s("DDx", { t("differential diagnosis") }),
	s("DFCI", { t("Dana-Farber Cancer Institute") }),
	s("DFS", { t("disease-free survival") }),
	s("DGC", { t("diffuse gastric cancer") }),
	s("DHAP", { t("dexamethasone(D), high-dose Ara C (HA, cytarabine), cisplatin (P)") }),
	s("DI", { t("diabetes insipidus") }),
	s("DIBH", { t("deep inspiratory breath hold") }),
	s("DIC", { t("disseminated intravascular coagulation") }),
	s("DIPG", { t("diffuse intrinsic pontine glioma") }),
	s("DKC", { t("dyskeratosis congenita") }),
	s("DLB", { t("diffuse large B-cell lymphoma") }),
	s("DLBCL", { t("diffuse large B-cell lymphoma") }),
	s("DLCO", { t("diffusing capacity for carbon monoxide") }),
	s("DLI", { t("donor lymphocyte infusion") }),
	s("DLT", { t("dose-limiting toxicity") }),
	s("DMSO", { t("dimethyl sulfoxide") }),
	s("DNA", { t("deoxyribonucleic acid") }),
	s("DOAC", { t("direct oral anticoagulant") }),
	s("DOR", { t("duration of response") }),
	s("DOTL1", { t("disruptor of telomeric silencing 1-like") }),
	s("DP", { t("dimerization partner") }),
	s("DP-IMRT", { t("dose-painted intensity-modulated radiation therapy") }),
	s("DRC", { t("dexamethasone, rituximab, cyclophosphamide") }),
	s("DRR", { t("digitally reconstructed radiographs") }),
	s("DS", { t("Down syndrome") }),
	s("DSB", { t("Double-strand break") }),
	s("DTIC", { t("Dacarbazine") }),
	s("DVHs", { t("Dose volume histograms") }),
	s("Del11q", { t("Deletion of chromosome 11q") }),
	s("Del13q", { t("Deletion of chromosome 13q") }),
	s("Del17p", { t("Deletion of chromosome 17p") }),
	s("Dexa", { t("Dexamethasone") }),
	s("Dur", { t("Duration") }),
	s("Dx", { t("Diagnosis") }),
	s("Dx'd", { t("Diagnosed") }),
	s("EBER", { t("EBV-encoded") }),
	s("EBRT", { t("external beam radiation therapy") }),
	s("EBUS", { t("endo bronchial ultrasound") }),
	s("EBUS", { t("endobronchial ultrasound") }),
	s("EBV", { t("Epstein–Barr virus") }),
	s("ECG", { t("electrocardiogram") }),
	s("ECHO", { t("echocardiogram") }),
	s("ECOG PS", { t("Eastern Cooperative Oncology Group Performance Status Classification") }),
	s("ECOG PS", { t("Eastern Cooperative Oncology Group Performance Status") }),
	s("ECP", { t("extracorporeal photopheresis") }),
	s("EDTA", { t("ethylenediaminetetraacetic acid") }),
	s("EEG", { t("electroencephalogram") }),
	s("EFS", { t("event-free survival") }),
	s("EGD", { t("esophagogastroduodenoscopy") }),
	s("EGF", { t("epidermal growth factor") }),
	s("EGFR", { t("epidermal growth factor receptor") }),
	s("EGFR", { t("epidermal growth factor receptor") }),
	s("EKG", { t("electrocardiogram") }),
	s("ELISA", { t("enzyme-linked immunosorbent assay") }),
	s("ELN", { t("European Leukemia Net") }),
	s("EMBX", { t("endometrial biopsy") }),
	s("EMG", { t("electromyography") }),
	s("EML4", { t("echinoderm microtubule-associated protein-like 4") }),
	s("EMR", { t("endoscopic mucosal resection") }),
	s("EMT", { t("epithelial to mesenchymal transition") }),
	s("EN", { t("extranodal") }),
	s("ENE", { t("extranodal extension") }),
	s("ENI", { t("elective nodal irradiation") }),
	s("EOC", { t("epithelial ovarian cancer") }),
	s("EOD", { t("extent of disease") }),
	s("EOI", { t("end of induction") }),
	s("EOL", { t("end of life") }),
	s("EORTC", { t("European Organisation for Research and Treatment of Cancer") }),
	s("EPO", { t("erythropoetin") }),
	s("EPP", { t("erythropoietic protoporphyria") }),
	s("ER", { t("estrogen receptor") }),
	s("ERCP", { t("endoscopic retrograde cholangiopancreatography") }),
	s("ERK", { t("extracellular signal-related kinase") }),
	s("ES", { t("Ewing sarcoma") }),
	s("ES-SCLC", { t("extensive stage small-cell lung cancer") }),
	s("ESA", { t("erythropoiesis stimulating agent") }),
	s("ESCC", { t("epidural spinal cord compression") }),
	s("ESD", { t("endoscopic submucosal dissection") }),
	s("ESFT", { t("Ewing sarcoma family of tumors") }),
	s("ESHAP", { t("etoposide (E), methylprednisone (S), high-dose cytarabine (HA), cisplatin (P)") }),
	s("ESRD", { t("end-stage renal disease") }),
	s("ET", { t("Essential thrombocythemia") }),
	s("ET", { t("endocrine therapy") }),
	s("ETT", { t("epithelioid trophoblastic tumor") }),
	s("EUA", { t("exam under anesthesia") }),
	s("EUS", { t("endoscopic ultrasound") }),
	s("EpCAM", { t("epithelial cell adhesion molecule") }),
	s("Eso", { t("esophageal") }),
	s("EtOH", { t("Ethanol") }),
	s("F-UMP", { t("fluorouridine monophosphosphate") }),
	s("F/N", { t("febrile neutropenia") }),
	s("FADD", { t("Fas-associated death domain") }),
	s("FAMMM", { t("Familial atypical multiple mole melanoma syndrome") }),
	s("FAP", { t("familial adenomatous polyposis") }),
	s("FASL", { t("FAS ligand") }),
	s("FDG", { t("fluorodeoxyglucose") }),
	s("FDR", { t("first-degree relative") }),
	s("FE", { t("fractional excretion") }),
	s("FEV1", { t("forced expiratory volume in one second") }),
	s("FFP", { t("fresh frozen plasma") }),
	s("FFPE", { t("Formalin-fixed paraffin-embedded") }),
	s("FFS", { t("failure-free survival") }),
	s("FGF23", { t("fibroblast growth factor-23") }),
	s("FGFR", { t("fibroblast growth factor receptor") }),
	s("FH", { t("favorable histology") }),
	s("FHx", { t("family history") }),
	s("FIGO", { t("International Federation of Obstetrics and Gynecology") }),
	s("FIS", { t("functional independent survival") }),
	s("FISH", { t("fluorescence in situ hybridization") }),
	s("FL", { t("follicular lymphoma") }),
	s("FLAIR", { t("fluid-attenuated inversion recovery") }),
	s("FLC", { t("free light chains") }),
	s("FLIPI", { t("follicular lymphoma international prognostic index") }),
	s("FNA", { t("fine needle aspiration") }),
	s("FNA", { t("fine-needle aspiration") }),
	s("FOBT", { t("fecal occult blood test") }),
	s("FOLFOX", { t("folinic acid, leucovorin, fluorouracil, oxaliplatin") }),
	s("FT", { t("fallopian tube(s)") }),
	s("FUO", { t("fever of unknown origin") }),
	s("FVL", { t("factor V Leiden") }),
	s("Fc", { t("fragment crystallizable region [of antibody]") }),
	s("FcR", { t("Fc receptor") }),
	s("FcgammaR", { t("Fcgamma receptor") }),
	s("FdUMP", { t("5-fluorodeoxyuridine monophosphate") }),
	s("Flu", { t("fludarabine") }),
	s("Fr", { t("fraction") }),
	s("Freq", { t("frequent") }),
	s("Fx", { t("fraction") }),
	s("G-CSF", { t("granulocyte colony-stimulating factor") }),
	s("G6PD", { t("glucose-6-phosphate") }),
	s("GA", { t("general anaesthesia") }),
	s("GAD", { t("glutamic acid decarboxylase") }),
	s("GAL9", { t("galectin-9") }),
	s("GBM", { t("glioblastoma multiforme") }),
	s("GBM", { t("glioblastoma") }),
	s("GC", { t("genetic counselor/counseling") }),
	s("GCSF", { t("granulocyte colony-stimulating factor") }),
	s("GCT", { t("germ cell tumor") }),
	s("GEM", { t("gemcitabine") }),
	s("GERD", { t("gastroesophageal reflux disease") }),
	s("GF", { t("growth factor") }),
	s("GFR", { t("glomerular filtration rate") }),
	s("GI", { t("gastrointestinal") }),
	s("GIB", { t("gastrointestinal bleeding") }),
	s("GIST", { t("gastrointestinal stromal tumor") }),
	s("GITR", { t("glucocorticoid-inducted TNFR-related protein") }),
	s("GJ", { t("gastrojejunostomy") }),
	s("GLD", { t("globoid cell leukodystrophy") }),
	s("GM-CSF", { t("granulocyte macrophage colony-stimulating factor") }),
	s("GMP", { t("good manufacturing practice") }),
	s("GNR", { t("gram-negative rods") }),
	s("GO", { t("gemtuzumab ozogamicin") }),
	s("GOC", { t("goal of care") }),
	s("GP", { t("glycoprotein") }),
	s("GPA", { t("graded prognostic assessment") }),
	s("GT", { t("genetic testing") }),
	s("GTR", { t("gross total resection") }),
	s("GTV", { t("gross Tumour Volume") }),
	s("GU", { t("genitourinary") }),
	s("GVD", { t("gemcitabine (G), vinorelbine (V), pegylated liposomal doxorubicin (D)") }),
	s("GVHD", { t("graft-versus-host disease") }),
	s("GVL", { t("graft-versus-leukemia") }),
	s("Gab", { t("GRB-associated binding protein") }),
	s("GemOx", { t("gemcitabine, oxaliplatin") }),
	s("Glc", { t("glucose") }),
	s("Glu", { t("glucose") }),
	s("Grb", { t("growth factor receptor-bound protein") }),
	s("GvH", { t("graft versus host") }),
	s("Gy", { t("Gray") }),
	s("H", { t("Herceptin/trastuzumab") }),
	s("H&N", { t("head and neck") }),
	s("H&P", { t("history and physical") }),
	s("H1RA", { t("histamine 1 receptor antagonist") }),
	s("H2RA", { t("histamine 2 receptor antagonist") }),
	s("HA", { t("headache") }),
	s("HAART", { t("highly active antiretroviral therapy") }),
	s("HART", { t("hyperfractionated accelerated radiotherapy") }),
	s("HBV", { t("hepatitis B virus") }),
	s("HBcAb", { t("hepatitis B core antibody") }),
	s("HBsAg", { t("hepatitis B surface antigen") }),
	s("HCC", { t("hepatocellular carcinoma") }),
	s("HCL", { t("hairy cell leukemia") }),
	s("HCLc", { t("classical hairy cell leukemia") }),
	s("HCP", { t("hereditary corpophyria") }),
	s("HCT", { t("hematopoietic cell transplantation") }),
	s("HCT-CI", { t("hematopoietic cell transplantation-specific comorbidity index") }),
	s("HCV", { t("hepatitis C virus") }),
	s("HD MTX", { t("high-dose methotrexate") }),
	s("HD", { t("hemodialysis") }),
	s("HDAC", { t("histone deacetylase") }),
	s("HDC", { t("high-dose chemotherapy") }),
	s("HDR", { t("high-dose rate") }),
	s("HDT/ASCR", { t("high-dose therapy/autologous stem cell rescue") }),
	s("HEENT", { t("head, eyes, ears, nose, throat") }),
	s("HELLP", { t("hemolysis, elevated liver enzymes, low platelet syndrome") }),
	s("HEP", { t("hepatoerythropoietic porphyria") }),
	s("HER", { t("human epidermal growth factor receptor") }),
	s("HER-2", { t("human epidermal growth factor receptor 2") }),
	s("HGF", { t("Hepatocyte growth factor") }),
	s("HGFR", { t("Hepatocyte growth factor receptor") }),
	s("HGG", { t("high-grade glioma") }),
	s("HGS", { t("high-grade serous ovarian cancer") }),
	s("HHV6", { t("human herpesvirus 6") }),
	s("HIAA", { t("5-hydroxyindoleacetic acid") }),
	s("HIF", { t("hypoxia inducible factor") }),
	s("HIPA", { t("heparin-induced platelet aggregation") }),
	s("HITT", { t("heparin-induced thrombocytopenia and thrombosis") }),
	s("HIV", { t("human immunodeficiency virus") }),
	s("HL", { t("hodgkin lymphoma") }),
	s("HLA Sp", { t("HLA-specificity") }),
	s("HLA", { t("human leukocyte antigen") }),
	s("HLH", { t("hemophagocytic") }),
	s("HNPCC", { t("hereditary non-polyposis colorectal cancer") }),
	s("HNSCC", { t("head and neck squamous cell cancer") }),
	s("HPT", { t("hyperparathyroidism") }),
	s("HPV", { t("human papillomavirus") }),
	s("HR", { t("Hazard ratio") }),
	s("HR", { t("homologous recombination") }),
	s("HR", { t("hormone receptor") }),
	s("HRD", { t("homologous recombination deficiency") }),
	s("HRQOL", { t("health-related quality of life") }),
	s("HRT", { t("hormone replacement therapy") }),
	s("HSC", { t("hematopoietic stem cells") }),
	s("HSCT", { t("hematopoietic stem cell transplantation") }),
	s("HSCs", { t("hematopoietic stem cells") }),
	s("HSM", { t("hepatosplenomegaly") }),
	s("HSR", { t("hypersensitivity reaction") }),
	s("HSV", { t("herpes simplex virus") }),
	s("HSV-1", { t("herpes simplex virus type 1") }),
	s("HTLV-1", { t("human T-lymphotrophic virus 1") }),
	s("HTN", { t("hypertension") }),
	s("HU", { t("hydroxyurea") }),
	s("HUS", { t("hemolytic uremic syndrome") }),
	s("HVA", { t("homovanillic acid") }),
	s("HVLT", { t("Hopkins Verbal Learning Test") }),
	s("Hb", { t("hemoglobin") }),
	s("Hct", { t("hematocrit") }),
	s("Hep", { t("hepatitis") }),
	s("Hgb", { t("hemoglobin") }),
	s("HoTN", { t("hypotension") }),
	s("HrHPV", { t("high-risk HPV") }),
	s("HypoNa", { t("hyponatremia") }),
	s("I&D", { t("incision and drainage") }),
	s("I-125", { t("Iodine-135") }),
	s("IABP", { t("intra-aortic balloon bump") }),
	s("IALT", { t("International Adjuvant Lung cancer Trial") }),
	s("IBD", { t("irritable bowel disease") }),
	s("IBW", { t("ideal body weight") }),
	s("ICANS", { t("immune effector cell-associated neurotoxicity syndrome") }),
	s("ICC", { t("intercostal catheter") }),
	s("ICE", { t("ifosfamide (I), carboplatin (C), etoposide (E)") }),
	s("ICI", { t("immune checkpoint inhibitors") }),
	s("ICOS", { t("inducible T-cell costimulatory") }),
	s("ICP", { t("intracranial pressure") }),
	s("ICU", { t("intensive care unit") }),
	s("ID", { t("infectious disease") }),
	s("IDA", { t("iron deficiency anemia") }),
	s("IDH", { t("isocitrate dehydrogenase") }),
	s("IFE", { t("immunofixation") }),
	s("IFLN", { t("inguinofemoral lymph node (LN)") }),
	s("IFLND", { t("inguinofemoral lymph node (LN) dissection") }),
	s("IFN", { t("interferon") }),
	s("IFN-g", { t("interferon gamma") }),
	s("IFND", { t("inguinal femoral lymph node dissection") }),
	s("IFRT", { t("involved-field radiation therapy") }),
	s("IGCCC", { t("international Germ Cell Consensus Classification") }),
	s("IGF", { t("insulin-like growth factor") }),
	s("IGFR1", { t("insulin-like growth factor receptor 1") }),
	s("IGHV", { t("immunoglobulin variable region heavy chain gene") }),
	s("IHC", { t("immunohistochemistry") }),
	s("IHC", { t("immunohistochemistry") }),
	s("IL", { t("interleukin") }),
	s("IL-6R", { t("interleukin 6 receptor") }),
	s("ILD", { t("interstitial lung disease") }),
	s("IMIDs", { t("immunomodulatory drugs") }),
	s("IMRT", { t("intensity-modulated radiation therapy") }),
	s("IMT", { t("inflammatory myofibroblastic tumor") }),
	s("INR", { t("international normalized ratio") }),
	s("IO", { t("immunotherapy") }),
	s("IP", { t("intraperitoneal") }),
	s("IPC", { t("indwelling pleural catheter") }),
	s("IPEX", { t("immunodysregulation polyendocrinopathy enteropathy X-linked syndrome") }),
	s("IPI", { t("international prognostic index") }),
	s("IPS", { t("idiopathic pneumonia syndrome") }),
	s("IPS", { t("international prognostic score") }),
	s("IR", { t("interventional radiology") }),
	s("IR", { t("ionizing radiation") }),
	s("IRR", { t("irradiated") }),
	s("ISH", { t("in situ hybridization") }),
	s("ISM", { t("indolent systemic mastocytosis") }),
	s("IST", { t("immunosuppressive therapy") }),
	s("IT", { t("intrathecal") }),
	s("ITD", { t("internal tandem repeat") }),
	s("ITP", { t("immune thrombocytopenic purpura") }),
	s("IU", { t("international units") }),
	s("IUP", { t("intrauterine pregnancy") }),
	s("IV", { t("intravenous") }),
	s("IVB", { t("intravenous bolus") }),
	s("IVE", { t("ifosfamide (I), epirubicin (V), etoposide (E)") }),
	s("IVF", { t("intravenous fluids") }),
	s("IVIG", { t("intravenous immunoglobulin") }),
	s("IVP", { t("intravenous push") }),
	s("Ig", { t("immunoglobulin") }),
	s("IgE", { t("immunoglobulin E") }),
	s("IgG", { t("immunoglobulin G") }),
	s("ImmTAC", { t("immune-mobilizing monoclonal TCR against cancer") }),
	s("Incl.", { t("including") }),
	s("Intraop", { t("intraoperative") }),
	s("Invest", { t("investigational") }),
	s("JAK", { t("Janus kinase") }),
	s("JC", { t("John Cunningham virus") }),
	s("Jxn", { t("junction") }),
	s("KIP", { t("kinase inhibitory protein") }),
	s("KIP2", { t("kinesin-like protein") }),
	s("KIR", { t("killer cell immunoglobulin-like receptor") }),
	s("KPS", { t("Karnofsky performance status") }),
	s("KS", { t("Kaposi sarcoma") }),
	s("L", { t("liter") }),
	s("LA", { t("lupus anticoagulant") }),
	s("LAC", { t("lupus anticoagulant") }),
	s("LACE", { t("lung adjuvant cisplatin evaluation") }),
	s("LAD", { t("lymphadenopathy") }),
	s("LAG3", { t("lymphocyte activation gene 3") }),
	s("LAMB", { t("liposomal amphotericin B") }),
	s("LAN", { t("lymphadenopathy") }),
	s("LAR", { t("low-anterior resection") }),
	s("LBL", { t("lymphoblastic lymphoma") }),
	s("LC", { t("local control") }),
	s("LCNS", { t("lung Cancer Nurse Specialist") }),
	s("LCWS", { t("low continuous wall suction") }),
	s("LD", { t("low dose") }),
	s("LDH", { t("lactate dehydrogenase") }),
	s("LDR", { t("low-dose rate") }),
	s("LE", { t("lower extremity") }),
	s("LEEP", { t("loop electrosurgical excision procedure") }),
	s("LFS", { t("Li–Fraumeni syndrome") }),
	s("LFT", { t("liver function tests") }),
	s("LGG", { t("low-grade glioma") }),
	s("LGL", { t("large granular lymphocytic") }),
	s("LHRH", { t("luteinizing-hormone-releasing hormone") }),
	s("LMN", { t("lower motor neuron") }),
	s("LMS", { t("leiomyosarcoma") }),
	s("LMWH", { t("low–molecular-weight heparin") }),
	s("LN", { t("lymph node") }),
	s("LND", { t("lymph node dissection") }),
	s("LOH", { t("loss of heterozygosity") }),
	s("LP", { t("lumbar puncture") }),
	s("LPD", { t("lymphoproliferative disorder") }),
	s("LR", { t("leukocyte reduced") }),
	s("LS", { t("Lynch syndrome") }),
	s("LS-SCLC", { t("limited stage small-cell lung cancer") }),
	s("LTBI", { t("latent tuberculosis infection") }),
	s("LUNG ART", { t("lung Adjuvant Radiotherapy Trial") }),
	s("LV", { t("left ventricle") }),
	s("LVEF", { t("left ventricular ejection fraction") }),
	s("LVI", { t("lymphovascular invasion") }),
	s("LVSI", { t("lymphovascular space invasion") }),
	s("Lin−", { t("lineage negative") }),
	s("M", { t("male") }),
	s("M-CSF", { t("macrophage colony-stimulating factor") }),
	s("MAC", { t("myeloablative conditioning") }),
	s("MAG", { t("myelin-associated glycoprotein") }),
	s("MAGE", { t("melanoma-associated antigen") }),
	s("MAHA", { t("microangiopathic hemolytic anemia") }),
	s("MALT", { t("mucosa-associated lymphoid tissue") }),
	s("MAO", { t("monoamine oxidase") }),
	s("MAP", { t("high-dose methotrexate (M), doxorubicin (A), cisplatin (P)") }),
	s("MAPK", { t("mitogen-activated protein kinase") }),
	s("MART-1", { t("melanoma antigen recognized by T-cells-1") }),
	s("MASCC", { t("multinational Association of Supportive Care in Cancer") }),
	s("MAb", { t("monoclonal antibody") }),
	s("MBL", { t("monoclonal B-cell lymphocytosis") }),
	s("MC", { t("mast cell") }),
	s("MCGP", { t("meaning Centered Group Psychotherapy") }),
	s("MCL", { t("mantle cell lymphoma") }),
	s("MDR", { t("multidrug resistance") }),
	s("MDS", { t("myelodysplastic syndrome") }),
	s("MDSCs", { t("myeloid-derived suppressor cells") }),
	s("MEC", { t("mucoepidermoid carcinoma") }),
	s("MEK", { t("mitogen-activated protein kinase") }),
	s("MF", { t("myelofibrosis") }),
	s("MFS", { t("metastases free survival") }),
	s("MG", { t("myasthenia gravis") }),
	s("MGMT", { t("methylguanine-DNA methyltransferase") }),
	s("MGUS", { t("monoclonal gammopathy of undetermined significance") }),
	s("MHC", { t("major histocompatibility complex") }),
	s("MI", { t("myocardial infarction") }),
	s("MIBG", { t("metaiodobenzylguanidine") }),
	s("MIPI", { t("mantle cell lymphoma international prognostic index") }),
	s("MIR", { t("morphine Immediate release") }),
	s("ML-DS", { t("myeloid leukemia of down syndrome") }),
	s("MLD", { t("mean total lung dose") }),
	s("MLD", { t("metachromatic leukodystrophy") }),
	s("MLH", { t("mutl homolog") }),
	s("MLH1", { t("MutL homolog 1 (mismatch repair system component)") }),
	s("MLH6", { t("MutS homolog 6 (mismatch repair system component)") }),
	s("MM", { t("multiple myeloma") }),
	s("MMAE", { t("monomethyl auristatin E") }),
	s("MMF", { t("mycophenolate mofetil") }),
	s("MMG", { t("mammogram") }),
	s("MMPs", { t("matrix metalloproteinases") }),
	s("MMR", { t("mismatch repair") }),
	s("MMRd", { t("mismatch repair deficiency") }),
	s("MMSE", { t("mini-mental status examination") }),
	s("MNZ", { t("metronidazole") }),
	s("MOF", { t("multiorgan failure") }),
	s("MOGTC", { t("malignant ovarian germ cell tumor") }),
	s("MPD", { t("myeloproliferative disorder") }),
	s("MPE", { t("malignant pleural effusion") }),
	s("MPN", { t("myeloproliferative neoplasms") }),
	s("MPNST", { t("malignant peripheral nerve sheath tumor") }),
	s("MR/MRI", { t("magnetic resonance imaging") }),
	s("MRC", { t("medical research council") }),
	s("MRCP", { t("magnetic resonance cholangiopancreatogrpahy") }),
	s("MRD", { t("matched related donor") }),
	s("MRD", { t("minimal residual disease") }),
	s("MRI", { t("magnetic resonance imaging") }),
	s("MRSA", { t("methicillin-resistant Staphylococcus aureus") }),
	s("MS", { t("mental status") }),
	s("MSC", { t("mesenchymal stem cells") }),
	s("MSH", { t("MutS homolog") }),
	s("MSH2", { t("MutS homolog 2 (mismatch repair system component)") }),
	s("MSI", { t("microsatellite") }),
	s("MSI-H", { t("microsatellite instability-high") }),
	s("MSKCC", { t("Memorial Sloan Kettering Cancer Center") }),
	s("MSS", { t("microsatellite stable") }),
	s("MSTS", { t("musculoskeletal tumor society") }),
	s("MTC", { t("medullary thyroid cancer") }),
	s("MTD", { t("multidisciplinary team") }),
	s("MTHFR", { t("methylene tetrahydrofolate reductase") }),
	s("MTX", { t("methotrexate") }),
	s("MUC-1", { t("mucin-1") }),
	s("MUC16", { t("mucine-16") }),
	s("MUD", { t("matched unrelated donor") }),
	s("MUGA", { t("multiple-gated acquisition scan") }),
	s("MZL", { t("marginal zone lymphoma") }),
	s("MaGIC", { t("malignant germ cell Tumor International Consortium") }),
	s("Mab", { t("monoclonal antibody") }),
	s("Me", { t("macrophage") }),
	s("Mel", { t("melphalan") }),
	s("Mets", { t("metastases") }),
	s("Mm/r", { t("morphine Modified release") }),
	s("Mt", { t("mutation") }),
	s("MΦ", { t("macrophage") }),
	s("N/C", { t("nuclear/cytoplasmic") }),
	s("NAC", { t("neoadjuvant chemotherapy") }),
	s("NAFLD", { t("nonalcoholic fatty liver disease") }),
	s("NASH", { t("nonalcoholic steatohepatitis") }),
	s("NB", { t("neuroblastoma") }),
	s("NBN", { t("nibrin") }),
	s("NCCN", { t("National Comprehensive Cancer Network") }),
	s("NCCTG", { t("North Central Cancer Treatment Group") }),
	s("NE", { t("neuroendocrine") }),
	s("NER", { t("nucleotide excision repair") }),
	s("NF-1", { t("neurofibromatosis type 1") }),
	s("NFALD", { t("nonalcoholic fatty liver disease") }),
	s("NG", { t("nasogastric") }),
	s("NGS", { t("next-generation sequencing") }),
	s("NHEJ", { t("nonhomologous end joining") }),
	s("NHL", { t("non-Hodgkin lymphoma") }),
	s("NI", { t("noninferiority") }),
	s("NK", { t("natural killer cell") }),
	s("NLPH", { t("nodular lymphocyte-predominant Hodgkin lymphoma") }),
	s("NMA", { t("nonmyeloablative") }),
	s("NMDA", { t("N-methyl-D-aspartate") }),
	s("NMDAR", { t("N-methyl D-aspartate receptor") }),
	s("NMDP", { t("National Marrow Donor Program") }),
	s("NMSC", { t("nonmelanoma skin cancer") }),
	s("NNH", { t("number needed to harm") }),
	s("NNT", { t("number needed to treat") }),
	s("NNTB", { t("number needed to benefit") }),
	s("NO", { t("nitric oxide") }),
	s("NOS", { t("not otherwise specified") }),
	s("NP", { t("nasopharynx") }),
	s("NPO", { t("nil per os") }),
	s("NRM", { t("nonrelapse mortality") }),
	s("NS", { t("normal saline") }),
	s("NSAID", { t("nonsteroidal anti-inflammatory drugs") }),
	s("NSAIDS", { t("non-steroidal anti-inflammatory drugs") }),
	s("NSCLC", { t("non-small cell lung cancer") }),
	s("NSE", { t("neuron-specific enolase") }),
	s("NTRK", { t("neurotrophic tyrosine receptor kinase") }),
	s("NY-ESO-1", { t("New York esophageal squamous cell carcinoma 1") }),
	s("NYHA", { t("New York Heart Association Heart Failure classification") }),
	s("Nivo", { t("nivolumab") }),
	s("OB", { t("obstetric") }),
	s("OIs", { t("opportunistic infections") }),
	s("OCP", { t("oral contraceptive pills") }),
	s("OFS", { t("ovarian function suppression") }),
	s("OGCT", { t("ovarian germ cell tumor") }),
	s("OKT3", { t("Muromonab-CD3") }),
	s("OMAS", { t("opsoclonus-myoclonus-ataxia syndrome") }),
	s("ONJ", { t("osteonecrosis of jaw") }),
	s("OP", { t("oropharynx") }),
	s("OR", { t("operating room") }),
	s("ORR", { t("overall response rate") }),
	s("OS", { t("overall survival") }),
	s("OTR", { t("organ transplant recipient") }),
	s("OV", { t("oncolytic virus") }),
	s("OX40L", { t("OX40 ligand") }),
	s("P-gp", { t("P-glycoprotein") }),
	s("PA", { t("posterior-anterior") }),
	s("PAH", { t("pulmonary arterial hypertension") }),
	s("PAI", { t("plasminogen activator inhibitor") }),
	s("PALB2", { t("partner and localizer of the BRCA2 gene") }),
	s("PAP", { t("prostatic acid phosphatase"), t("Pulmonary alveolar proteinosis") }),
	s("PARP", { t("poly (ADP-ribose) polymerase") }),
	s("PARPi", { t("PARP inhibitors") }),
	s("PAS", { t("platelet additive solution") }),
	s("PAX8", { t("paired Box 8 gene") }),
	s("PB", { t("peripheral blood") }),
	s("PBG", { t("porphobilinogen") }),
	s("PBMC", { t("peripheral blood mononuclear cell") }),
	s("PBSC", { t("peripheral blood stem cells") }),
	s("PBSCT", { t("peripheral blood stem cell transplant") }),
	s("PC", { t("protein C") }),
	s("PCALCL", { t("primary cutaneous anaplastic large-cell lymphoma") }),
	s("PCI", { t("prophylactic cranial irradiation") }),
	s("PCN", { t("penicillin") }),
	s("PCNSL", { t("primary central nervous system lymphoma") }),
	s("PCOS", { t("polycystic ovary syndrome") }),
	s("PCR", { t("polymerase chain reaction") }),
	s("PCT", { t("porphyria cutanea tarda") }),
	s("PCV", { t("procarbazine, lomustine and vincristine") }),
	s("PD", { t("progressive disease") }),
	s("PD-1", { t("programmed cell death protein 1") }),
	s("PD-L1", { t("programmed death ligand 1") }),
	s("PD-L1/2", { t("programmed death-ligand 1/2") }),
	s("PDGFRa", { t("platelet-derived growth factor receptor alpha") }),
	s("PDT", { t("photodynamic therapy") }),
	s("PEG", { t("percutaneous endoscopic gastrostomy") }),
	s("PET", { t("positron emission tomography") }),
	s("PET/CT", { t("positron emission tomography–computerized tomography") }),
	s("PF24", { t("plasma frozen within 24 hours after phlebotomy") }),
	s("PF4", { t("platelet factor 4") }),
	s("PFA", { t("platelet function analyzer") }),
	s("PFS", { t("progression-free survival") }),
	s("PFT", { t("pulmonary function test") }),
	s("PGD", { t("preimplantation genetic diagnosis") }),
	s("PGE2", { t("prostaglandin E2") }),
	s("PGT", { t("preimplantation testing") }),
	s("PI", { t("prognostic index") }),
	s("PI3K", { t("phosphinositide 3-kinase") }),
	s("PID", { t("primary immunodeficiency disorder") }),
	s("PJP", { t("pneumocystis jiroveci pneumonia") }),
	s("PK/PD", { t("pharmacokinetics/pharmacodynamics") }),
	s("PLCO", { t("prostate, Lung, Colorectal and Ovarian Cancer Screening Trial") }),
	s("PLCg", { t("phospholipase C gamma") }),
	s("PLEX", { t("plasma exchange") }),
	s("PLL", { t("prolymphocytic leukemia") }),
	s("PMRT", { t("postmastectomy radiation therapy") }),
	s("PMS2", { t("PMS1 homolog 2 (mismatch repair system component)") }),
	s("PNA", { t("pneumonia") }),
	s("PNET", { t("primitive neuroectodermal tumor") }),
	s("PNH", { t("paroxysmal nocturnal hemoglobinuria") }),
	s("PNI", { t("perineural") }),
	s("PO", { t("per os") }),
	s("PO4", { t("phosphate") }),
	s("POD", { t("progression of disease") }),
	s("POMA", { t("postoperative margin assessment") }),
	s("PORT", { t("postoperative external beam radiotherapy") }),
	s("PPES", { t("palmoplantar erythrodysesthesia") }),
	s("PPI", { t("proton pump inhibitor") }),
	s("PR", { t("partial response") }),
	s("PR", { t("progesterone receptor") }),
	s("PRES", { t("posterior reversible encephalopathy syndrome") }),
	s("PS", { t("performance status") }),
	s("PS", { t("performance status") }),
	s("PSA", { t("prostate-specific antigen") }),
	s("PSMA", { t("prostate-specific membrane antigen") }),
	s("PSTT", { t("placental site trophoblastic tumor") }),
	s("PT", { t("prothrombin time") }),
	s("PTCL", { t("peripheral T-cell lymphoma") }),
	s("PTCy", { t("posttransplant cyclophosphamide") }),
	s("PTEN", { t("phosphatase and tensin homolog") }),
	s("PTG", { t("prothrombin gene") }),
	s("PTH", { t("parathyroid hormone") }),
	s("PTHrP", { t("parathyroid-related protein") }),
	s("PTLD", { t("posttransplant lymphoproliferative disease") }),
	s("PTO", { t("percutaneous transhepatic obliteration") }),
	s("PTT", { t("partial thromboplastin time") }),
	s("PTV", { t("planning Target Volume") }),
	s("PUVA", { t("psoralen plus ultraviolet A") }),
	s("PV", { t("polycythemia vera"), t("Portal vein") }),
	s("PVR", { t("poliovirus receptor") }),
	s("PXA", { t("pleomorphic xanthoastrocytoma") }),
	s("Panadol", { t("acetaminophen") }),
	s("Path", { t("pathology") }),
	s("Pathophys", { t("pathophysiology") }),
	s("Pd-103", { t("Palladium-103") }),
	s("Pembro", { t("pembrolizumab") }),
	s("Ph", { t("philadelphia") }),
	s("Pheo", { t("pheochromocytoma") }),
	s("Plat", { t("platinum") }),
	s("Plt", { t("platelet") }),
	s("Post-op", { t("postoperative") }),
	s("Post.", { t("posterior") }),
	s("Ppx", { t("prophylaxis") }),
	s("Prev", { t("previous") }),
	s("Prog", { t("prognosis") }),
	s("Prox", { t("proximal") }),
	s("Pulm", { t("pulmonary") }),
	s("QA", { t("quality assurance") }),
	s("QALY", { t("quality Adjusted Life Years") }),
	s("QD", { t("daily") }),
	s("QOL", { t("quality of life") }),
	s("QUANTEC", { t("Quantitative Analysis of Normal Tissue Effects in the Clinic") }),
	s("QoL", { t("quality of life") }),
	s("R", { t("rituximab") }),
	s("R-CHOP", { t("rituximab (R), cyclophosphamide (C), doxorubicin (H), vincristine (O), prednisone (P)") }),
	s("R/R", { t("relapse/refractory") }),
	s("R/o", { t("rule out") }),
	s("R0", { t("complete resection with negative microscopic margins") }),
	s("R1", { t("microscopically positive margins") }),
	s("RAD51", { t("RAD51 recombinase") }),
	s("RAD51C/D", { t("RAD51 Paralog C or D") }),
	s("RANO", { t("response assessment in neuro-oncology") }),
	s("RAR", { t("retinoic acid receptor") }),
	s("RARS", { t("refractory anemia with ring sideroblasts") }),
	s("RARS-T", { t("refractory anemia with ring sideroblasts with thrombocytosis") }),
	s("RB", { t("retinoblastoma") }),
	s("RB1", { t("retinoblastoma protein") }),
	s("RBC", { t("red blood cell") }),
	s("RBE", { t("relative biologic effectiveness") }),
	s("RCC", { t("renal cell carcinoma") }),
	s("RCT", { t("randomised controlled trial") }),
	s("RCT", { t("randomized controlled trial") }),
	s("REMS", { t("risk evaluation and mitigation strategies") }),
	s("RF", { t("risk factor") }),
	s("RFA", { t("Radiofrequency ablation") }),
	s("RFA", { t("Radiofrequency ablation") }),
	s("RFS", { t("Recurrence-free survival") }),
	s("RIC", { t("Reduced intensity conditioning") }),
	s("RMSF", { t("Rocky mountain spotted fever") }),
	s("RNA", { t("ribonucleic acid") }),
	s("RNAi", { t("RNA interference") }),
	s("RP", { t("retroperitoneal") }),
	s("RPA", { t("recursive partitioning analysis") }),
	s("RR", { t("relative risk or Response rate") }),
	s("RR", { t("response rate") }),
	s("RRSO", { t("risk-reducing salpingo-oophorectomy") }),
	s("RS", { t("recurrence score") }),
	s("RSV", { t("respiratory syncytial virus") }),
	s("RT", { t("radiation therapy"), t("Richter’s transformation") }),
	s("RT", { t("radiotherapy") }),
	s("RT-PCR", { t("reverse transcription-polymerase chain reaction") }),
	s("RTK", { t("receptor tyrosine kinase") }),
	s("RTOG", { t("radiation Therapy Oncology Group") }),
	s("RTOG", { t("radiation therapy oncology group") }),
	s("RUQ", { t("right upper quadrant") }),
	s("Rec", { t("recommended") }),
	s("Retic-He", { t("reticulocyte hemoglobin equivalent") }),
	s("Rx", { t("therapy") }),
	s("S", { t("south") }),
	s("S/s", { t("signs/symptoms") }),
	s("SABR", { t("stereotactic ablative radiotherapy") }),
	s("SABR", { t("stereotactic ablative radiotherapy") }),
	s("SBDS", { t("Shwachman–Diamond syndrome") }),
	s("SBE", { t("self-breast exam") }),
	s("SBP", { t("systolic blood pressure") }),
	s("SBRT", { t("stereotactic body radiotherapy") }),
	s("SC/SQ", { t("subcutaneous") }),
	s("SCC", { t("squamous cell carcinoma") }),
	s("SCC", { t("squamous cell carcinoma") }),
	s("SCCHN", { t("squamous cell carcinoma of the head and neck") }),
	s("SCF", { t("stem cell factor") }),
	s("SCID", { t("severe combined immunodeficiency") }),
	s("SCLC", { t("small cell lung cancer") }),
	s("SCLC", { t("small-cell lung cancer") }),
	s("SCLC-ES", { t("small cell lung cancer - extensive stage") }),
	s("SCLC-LS", { t("small cell lung cancer - limited stage") }),
	s("SCT", { t("stem-cell transplantation") }),
	s("SD", { t("stable disease") }),
	s("SDC", { t("salivary duct carcinoma") }),
	s("SE", { t("Sensitivity") }),
	s("SE", { t("side effect") }),
	s("SEER", { t("surveillance, Epidemiology and End Results") }),
	s("SEGA", { t("subependymal giant cell astrocytoma") }),
	s("SERD", { t("selective estrogen receptor down-regulator") }),
	s("SGP", { t("supportive group psychotherapy") }),
	s("SIADH", { t("syndrome of inappropriate antidiuretic hormone") }),
	s("SINS", { t("spinal instability neoplastic score") }),
	s("SIRP-1", { t("signal regulatory protein-1") }),
	s("SIRPa", { t("signal regulatory protein alpha") }),
	s("SIRS", { t("systemic inflammatory response syndrome") }),
	s("SLD", { t("single lineage dysplasia") }),
	s("SLE", { t("systemic lupus erythematous") }),
	s("SLL", { t("small lymphocytic lymphoma") }),
	s("SM-AHN", { t("systemic mastocytosis with associated hematologic neoplasm") }),
	s("SMA", { t("smooth muscle actin") }),
	s("SMD", { t("standardised mean difference") }),
	s("SMITE", { t("simultaneous multiple interaction T-cell engaging") }),
	s("SMV", { t("superior mesenteric vein") }),
	s("SMZL", { t("splenic marginal zone lymphoma") }),
	s("SNLB", { t("sentinel lymph node biopsy") }),
	s("SNP", { t("single nucleotide polymorphism") }),
	s("SNUC", { t("sinonasal undifferentiated carcinoma") }),
	s("SOC", { t("standard of care") }),
	s("SOS", { t("sinusoidal obstruction syndrome") }),
	s("SPEP", { t("serum protein electrophoresis") }),
	s("SPTCL", { t("subcutaneous panniculitis-like T-cell lymphoma") }),
	s("SR", { t("standard risk") }),
	s("SRA", { t("serotonin release assay") }),
	s("SRE", { t("skeletal related events") }),
	s("SRS", { t("stereotactic radiosurgery") }),
	s("SS", { t("Sézary syndrome") }),
	s("SSB", { t("Single-strand break") }),
	s("SSM", { t("smoldering systemic mastocytosis") }),
	s("SSRI", { t("selective serotonin reuptake inhibitors") }),
	s("SSTI", { t("skin and soft tissue infection") }),
	s("STAT3", { t("signal transducer and activator of transcription 3") }),
	s("STI", { t("sexually transmitted infection") }),
	s("STIC", { t("serous tubal intraepithelial carcinoma") }),
	s("STK11", { t("serine/threonine kinase 11") }),
	s("STS", { t("soft tissue sarcoma") }),
	s("SVC", { t("superior vena cava") }),
	s("Sev.", { t("severe") }),
	s("Shh", { t("sonic hedgehog") }),
	s("Sn", { t("sensitivity"), t("Sign") }),
	s("Sp", { t("specificity") }),
	s("Stim", { t("stimulation") }),
	s("Sx", { t("symptom") }),
	s("T", { t("taxane") }),
	s("T(1/2)", { t("half-life") }),
	s("T-DM1", { t("trastuzumab emtansine") }),
	s("T-Dxd", { t("trastuzumab deruxtecan") }),
	s("T-VEC", { t("talimogene laherparepvec") }),
	s("T. Bili", { t("total bilirubin") }),
	s("T/C", { t("paclitaxel (T), carboplatin (C)") }),
	s("T/FL", { t("transformed follicular lymphoma") }),
	s("T4", { t("thyroxine") }),
	s("TACE", { t("transarterial chemoembolization") }),
	s("TAE", { t("transcathether arterial embolisation") }),
	s("TAH", { t("total abdominal hysterectomy") }),
	s("TAH/BSO", { t("total abdominal hysterectomy/bilateral salpino-oophorectomy") }),
	s("TAM", { t("tumor-associated macrophage") }),
	s("TAP", { t("paclitaxel (T), doxorubicin (A), cisplatin (P)") }),
	s("TAR", { t("thrombocytopenia with absent radius syndrome") }),
	s("TARE", { t("transarterial radioembolization") }),
	s("TAT", { t("turnaround time") }),
	s("TB", { t("total bilirubin") }),
	s("TBBx", { t("transbronchial biopsy") }),
	s("TBI", { t("total body irritation") }),
	s("TCA", { t("tricyclic antidepressant(s)") }),
	s("TCGA", { t("The Cancer Genome Atlas Program") }),
	s("TCR", { t("T-cell receptor") }),
	s("TEPA", { t("tetraethylenepentamine") }),
	s("TF", { t("transcription factor") }),
	s("TFT", { t("thyroid function test") }),
	s("TGFb", { t("transforming growth factor beta") }),
	s("TGs", { t("triglycerides") }),
	s("TIGIT", { t("T-cell immunoglobulin and ITIM domain") }),
	s("TIL(s)", { t("Tumor-infiltrating lymphocyte(s)") }),
	s("TIM3", { t("T-cell immunoglobulin and mucin-domain containing-3") }),
	s("TIW", { t("Three times a week") }),
	s("TK", { t("tyrosine kinase") }),
	s("TKD", { t("tyrosine kinase domains") }),
	s("TKI", { t("tyrosine kinase inhibitor") }),
	s("TKIs", { t("tyrosine kinase inhibitors") }),
	s("TLS", { t("tumor lysis syndrome") }),
	s("TMA", { t("thrombotic microangiopathy") }),
	s("TMD", { t("transient myeloproliferative disorder") }),
	s("TME", { t("tumor microenvironment") }),
	s("TMP-SMX", { t("trimethoprim-sulfamethoxazole") }),
	s("TMZ", { t("temozolomide") }),
	s("TNBC", { t("triple-negative breast cancer") }),
	s("TNF", { t("tumor necrosis factor") }),
	s("TNFR1", { t("tumor necrosis factor receptor 1") }),
	s("TNFa", { t("tumor necrosis factor alpha") }),
	s("TP53", { t("tumor protein p53") }),
	s("TPC", { t("tunnelled pleural catheter") }),
	s("TPN", { t("total parenteral nutrition") }),
	s("TPO", { t("thrombopoietin") }),
	s("TPO-RA", { t("thrombopoietin receptor agonist") }),
	s("TRADD", { t("tumor necrosis factor receptor type 1–associated death domain") }),
	s("TSC", { t("tuberous sclerosis complex") }),
	s("TSEB", { t("total skin electron beam") }),
	s("TSG", { t("tumor suppressor gene") }),
	s("TSH", { t("thyroid-stimulating hormone") }),
	s("TTE", { t("transthoracic echocardiography") }),
	s("TTP", { t("thrombotic thrombocytopenic purpura") }),
	s("TVUS", { t("transvaginal ultrasound") }),
	s("Tam", { t("tamoxifen") }),
	s("Tc99", { t("technetium-99") }),
	s("Thio", { t("thiotepa") }),
	s("Tox", { t("toxicity") }),
	s("Toxo", { t("toxoplasmosis") }),
	s("Treg", { t("regulatory T cells") }),
	s("TriKE", { t("trispecific killer engager") }),
	s("Tx", { t("treatment") }),
	s("U/A", { t("urinalysis") }),
	s("U/S", { t("ultrasound") }),
	s("UA", { t("uric acid") }),
	s("UFH", { t("unfractionated heparin") }),
	s("UGI", { t("upper gastrointestinal") }),
	s("UH", { t("unfavorable histology") }),
	s("UKCTOCS", { t("United Kingdom Collaborative Trial of Ovarian Cancer Screening") }),
	s("ULN", { t("upper limit of normal") }),
	s("UMN", { t("upper motor neuron") }),
	s("UOP", { t("urine output") }),
	s("UOsm", { t("urine osmolarity") }),
	s("UPEP", { t("urine protein electrophoresis") }),
	s("UPS", { t("undifferentiated pleomorphic sarcoma") }),
	s("URD", { t("unrelated donor") }),
	s("URI", { t("upper respiratory tract infection") }),
	s("UROD", { t("uroporphyrinogen decarboxylase") }),
	s("US", { t("united States") }),
	s("USPSTF", { t("united States Preventive Services Task Force") }),
	s("UV", { t("ultraviolet") }),
	s("UVA", { t("ultraviolet A") }),
	s("UVB", { t("ultraviolet B") }),
	s("Ucortisol", { t("Urine cortisol") }),
	s("VAC", { t("vincristine (V), dactinomycin (A), and cyclophosphamide (C)") }),
	s("VAF", { t("Variant allele frequency") }),
	s("VAI", { t("vincristine (v), dactinomycin (D), and ifosfamide (I)") }),
	s("VAS", { t("Visual analogue scale") }),
	s("VATS", { t("Video-assisted thoracic surgery") }),
	s("VCR", { t("vincristine") }),
	s("VEGF", { t("vascular endothelial growth factor") }),
	s("VEGF", { t("vascular endothelial growth factor") }),
	s("VEGFR", { t("VEGF receptor") }),
	s("VEGFinhib", { t("VEGF inhibitor") }),
	s("VGCC", { t("voltage-gated calcium channel") }),
	s("VGKC", { t("voltage-gated potassium channel") }),
	s("VGPR", { t("very good partial response") }),
	s("VHL", { t("von Hippel–Lindau") }),
	s("VIDE", { t("vincristine (V), ifosfamide (I), doxorubicin (D), and etoposide (E)") }),
	s("VIN", { t("vulvar intraepithelial neoplasia") }),
	s("VIP", { t("vasoactive intestinal peptide") }),
	s("VISTA", { t("V-domain Ig suppressor of T-cell activation") }),
	s("VISTA-R", { t("V-domain Ig suppressor of T-cell activation receptor") }),
	s("VKA", { t("vitamin k antagonist") }),
	s("VMA", { t("vanillylmandelic acid") }),
	s("VOC", { t("vaso-occlusive crisis") }),
	s("VOD", { t("veno-occlusive disease") }),
	s("VP", { t("variegate porphyria") }),
	s("VRE", { t("vancomycin resistant enterococcus") }),
	s("VS", { t("vital signs") }),
	s("VTE", { t("venous thromboembolism") }),
	s("VZV", { t("varicella-zoster virus") }),
	s("WAGR", { t("Wilms tumor, aniridia, genitourinary, range of developmental delays") }),
	s("WBC", { t("white blood cell") }),
	s("WBMRI", { t("whole-body MRI") }),
	s("WBRT", { t("Whole brain radiotherapy") }),
	s("WHO", { t("World Health Organization") }),
	s("WLL", { t("whole lung lavage") }),
	s("WM", { t("Waldenstrom macroglobulinemia") }),
	s("WNT", { t("wingless INT") }),
	s("WT1", { t("Wilms tumor 1 gene") }),
	s("Wk(s)", { t("week(s)") }),
	s("XLDPP", { t("X-linked dominant protoporphyria") }),
	s("XPC", { t("xeroderma pigmentosum complementation group C") }),
	s("XR", { t("X-ray") }),
	s("YAP", { t("Yes-associated protein") }),
	-- lower case
	s("a/w", { t("associated with") }),
	s("aCTLA-4", { t("anti-cytotoxic T-lymphocyte antigen 4") }),
	s("aPC", { t("activated protein C") }),
	s("aPD-L1", { t("anti-programmed death-ligand 1") }),
	s("aPD—1", { t("anti-programmed death 1") }),
	s("aPTT", { t("activated partial thromboplastin time") }),
	s("aa", { t("amino acid") }),
	s("abd", { t("abdominal") }),
	s("abnl", { t("abnormal") }),
	s("add’l", { t("Additional") }),
	s("adv", { t("advanced") }),
	s("ag", { t("antigen") }),
	s("alk phos", { t("Alkaline phosphatase") }),
	s("allo", { t("allogeneic") }),
	s("allo-SCT", { t("Allogeneic stem cell transplant") }),
	s("amp", { t("Amplification") }),
	s("approx", { t("approximately") }),
	s("assoc.", { t("associated") }),
	s("auto", { t("autologous") }),
	s("avg", { t("average") }),
	s("b-hCG", { t("beta human chorionic gonadotropin") }),
	s("b/w", { t("between") }),
	s("bp", { t("base pair") }),
	s("btw", { t("between") }),
	s("bx", { t("biopsy") }),
	s("c/w", { t("compared with") }),
	s("cDNA", { t("complementary DNA") }),
	s("cGVHD", { t("chronic graft-versus-host disease") }),
	s("cGy", { t("centi-Gray") }),
	s("ccRCC", { t("clear-cell renal cell cancer/clear cell renal cell carcinoma") }),
	s("chemo", { t("chemotherapy") }),
	s("cm", { t("centimeter") }),
	s("coag", { t("coagulation") }),
	s("conc.", { t("concentration") }),
	s("costim", { t("costimulatory") }),
	s("cum.", { t("cumulative") }),
	s("cyto", { t("cytogenetics") }),
	s("d/o", { t("disorder") }),
	s("d/t", { t("due to") }),
	s("dNTP", { t("deoxyribonucleotide triphosphate") }),
	s("dab", { t("dabrafenib") }),
	s("dauno", { t("daunorubicin") }),
	s("ddNTP", { t("dideoxynucleotide triphosphate") }),
	s("decr", { t("decreased") }),
	s("derm", { t("dermatologic") }),
	s("dex", { t("dexamethasone") }),
	s("dz", { t("disease") }),
	s("ed.", { t("edition") }),
	s("eg", { t("for example") }),
	s("enco", { t("encorafenib") }),
	s("eos", { t("eosinophils") }),
	s("esp", { t("especially") }),
	s("fn", { t("function") }),
	s("fxn", { t("function") }),
	s("g/dL", { t("grams per deciliter") }),
	s("gp100", { t("glycoprotein 100") }),
	s("gyn", { t("gynecologic") }),
	s("h", { t("hour") }),
	s("h/o", { t("history of") }),
	s("hTERT", { t("human telomerase reverse transcriptase") }),
	s("hx", { t("history") }),
	s("hydrea", { t("hydroxyurea") }),
	s("hyperCA", { t("hypercalcemia") }),
	s("hyperCVAD", { t("hyper-fractionated") }),
	s("incr.", { t("increased") }),
	s("infx", { t("infection") }),
	s("infxn", { t("infection") }),
	s("ipi", { t("ipilimumab") }),
	s("irAEs", { t("immune-related adverse events") }),
	s("iwCLL", { t("International Workshop on Chronic Lymphocytic Leukemia") }),
	s("kb", { t("kilobase") }),
	s("m2", { t("square meter") }),
	s("mEq", { t("milliequivalents") }),
	s("mGluR1", { t("metabotropic glutamate receptor 1") }),
	s("mL", { t("milliliter") }),
	s("mL/d", { t("milliliter per day") }),
	s("mRNA", { t("messenger RNA") }),
	s("mTOR", { t("mammalian target of rapamycin") }),
	s("max", { t("maximum") }),
	s("memb", { t("membrane") }),
	s("mg", { t("milligram") }),
	s("mgmt", { t("management") }),
	s("mo", { t("medical oncology") }),
	s("mo", { t("month") }),
	s("n/v", { t("nausea/vomiting") }),
	s("nAChR", { t("nicotinic acetylcholine receptor") }),
	s("neb", { t("nebulizer") }),
	s("neg", { t("negative") }),
	s("neoadj", { t("neoadjuvant") }),
	s("ng", { t("nanogram") }),
	s("nl", { t("normal") }),
	s("p/w", { t("presents with") }),
	s("pCR", { t("pathologic complete response") }),
	s("pRBC", { t("packed red blood cells") }),
	s("perf", { t("perforation") }),
	s("perm", { t("permeability") }),
	s("poss", { t("possible") }),
	s("pre-op", { t("preoperative") }),
	s("prot", { t("protein") }),
	s("psy", { t("psychiatric") }),
	s("px", { t("prognosis") }),
	s("qPCR", { t("quantitative polymerase chain reaction") }),
	s("r/o", { t("rule out") }),
	s("r/r", { t("relapsed/refractory") }),
	s("rRNA", { t("ribosomal RNA") }),
	s("rad onc", { t("radiation oncology") }),
	s("rrBLM", { t("risk-reducing bilateral mastectomy") }),
	s("rrBSO", { t("risk-reducing bilateral oophorectomy") }),
	s("rxn", { t("reaction") }),
	s("s/e", { t("side effect") }),
	s("s/p", { t("status post") }),
	s("sBCC", { t("superficial BCC") }),
	s("scFv", { t("single-chain variable fragment") }),
	s("seq", { t("sequence") }),
	s("subop", { t("suboptimally debulked") }),
	s("syn", { t("syndrome") }),
	s("unfav.", { t("unfavorable") }),
	s("usu", { t("usually") }),
	s("vWD", { t("von Willebrand Disease") }),
	s("vWF", { t("von Willebrand factor") }),
	s("vem", { t("vemurafenib") }),
	s("vit", { t("vitamin") }),
	s("w/", { t("with") }),
	s("w/c", { t("which can") }),
	s("w/in", { t("within") }),
	s("w/o", { t("without") }),
	s("w/u", { t("work-up") }),
	s("well-diff", { t("well-differentiated") }),
	s("wk", { t("week") }),
	s("wt", { t("weight") }),
	s("wt", { t("weight") }),
	s("y", { t("year(s)") }),
	s("VDC/IE", {
		t(
			"vincristine (V), doxorubicin (D), and cyclophosphamide (C) alternating with Ifosfamide (I) and etoposide (E)"
		),
	}),
	s(
		"R-EPOCH",
		{ t("Rituximab (R), etoposide (E), prednisone (P), vincristine (O), cyclophosphamide (C), doxorubicin (H)") }
	),
	s(
		"daEPOCH",
		{ t("dose-adjusted etoposide (E), prednisone (P), vincristine (O), cyclophosphamide (C), doxorubicin (H)") }
	),
	s("VPEFR", {
		t(
			"V (involvement of vena cava), P (portal bifurcation), E (extrahepatic contiguous extension), F (multifocal liver tumor), R (tumor rupture)"
		),
	}),
}
