matches:
  - trigger: ".addbib"
    replace: "根據你已經查到的文章內容，以markdown風格 i.e. [1],[2-3] 在文章中加入該引用，並在文章後加入引用列表，以包含 DOI 的 AMA 格式"
  - trigger: ".hy"
    replace: "highlight the high-yield oncology key points for board exams"
  - trigger: ".pk"
    replace: "convert the context as Pocket Medicine styled text with nested list,  plain text, no markdown strong syntax, indent use 4 space, '- ' as the list marker, you can  use ↑↓ (for increase/decrease) →←Δ w/ w/o incl. ∵ ∴ ✔ (for check,approval) ✘ (no, not), ㊀ for negative, ㊉ for positive, these symbol or abbr for shortening line, adj. for adjuvant, s/p for after, return result in a codebox"
  - trigger: ".zh"
    replace: "convert the context as Pocket Medicine styled text with nested list,  plain text, no markdown strong syntax, indent use 4 space, '- ' as the list marker, you can  use ↑↓ (for increase/decrease) →←Δ w/ w/o incl. ∵ ∴ ✔ (for check,approval) ✘ (no, not), ㊀ for negative, ㊉ for positive, these symbol or abbr for shortening line, adj. for adjuvant, s/p for after, return result in a codebox, 以繁體中文的文法結構來寫每一個語句，但不用翻譯專有名詞，以維持符合台灣醫師習慣的可讀性"
  - trigger: ".tw"
    replace: "以繁體中文的文法結構來書寫內容，但不翻譯專有名詞。以所謂醫療晶晶體，以維持符合台灣醫師習慣的可讀性"
  - trigger: ".top"
    replace: "Summarize this progress note into exactly 3 lines, 1st line: the oncology styled diagnose, 2nd line: reason for admission, 3rd line: current status,  Use html tag <BR> literally for line breaks, add a → at begining of each line, use as much abbr as possible (this is for a hand-off, so be concise), in English, return the final result in a codebox"
  - trigger: "#blue"
    replace: "#3D6869"
  - trigger: ":clipboardtest"
    replace: "\"$|$\",\"{{clipboard}}\""
    vars:
      - name: "clipboard"
        type: "clipboard"
  - trigger: "ymd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "mmdd"
    replace: "({{mydate}})"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m-%d"
  - trigger: "/review"
    replace: |
      (""$|$[title])
      AND ("N Engl J Med"[jour] OR "Lancet"[jour] OR "JAMA"[jour] OR "BMJ"[jour] OR "Ann Intern Med"[jour] OR "Intensive Care Medicine"[jour] OR "Nat Rev Dis Primers"[jour])
      AND ("Case Reports"[Publication Type] OR "review"[Publication Type]) AND "last 10 years"[EDat]
  - trigger: "bitly"
    replace: "bit.ly/"
  - trigger: "gitcommit"
    replace: "git commit \"$|$ {{mydate}}\""
    vars:
      - name: mydate
        type: date
        params:
          format: "%y-%m-%d %H:%M"
  # Shell commands
  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
  - trigger: "::short"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "$HOME/.pyenv/versions/keyboardmaestro/bin/python  $HOME/pyscripts/bitly.py"
  - trigger: ":whichpy"
    replace: "$HOME/.pyenv/versions/$|$/bin/python"
  - trigger: ":blank"
    replace: "⠀⠀⠀⠀⠀⠀⠀⠀"
  - trigger: "pyenv:bin"
    replace: "$HOME/.pyenv/versions/$|$/bin/python"
  - trigger: "ft1"
    replace: "†"
  - trigger: "ft2"
    replace: "††"
  - trigger: "ft3"
    replace: "¶"
  - trigger: "ft4"
    replace: "§"
  - trigger: "fuckyou"
    replace: "我想這部分，還是要跟余先生討論後再決定"
    #
# other files:
# facebook.yml
