matches:
  - trigger: "speaker.note"
    replace: "這張圖為什麼要設計成這樣？想傳達的精神是？我在報簡報時怎麼說？"
  - trigger: ".astxt"
    replace: "Return only the plain text inside a txt code block for easy copying. nothing else."
  - trigger: ".oncology"
    replace: "Summarize as an oncologist with section titles (h1, no numbering): patient info, cancer type, grade, stage (TNM), genetic mutations, disease course (start with ‘Initial presentation’, each event as ‘- (YYYY-MM-DD): event, treatment’, group by time), and reason for hospitalization in bullet points."
  - trigger: ".plan"
    replace: "List next steps for evaluation and treatment (<20 words each); include specific drug names with dosage and precise blood tests; use ‘-’ for each item, plain text, no markdown syntax."
  - trigger: ".ddx"
    replace: "List differential diagnoses with concise reasoning (<20 words each); include both supporting and rejecting points for each; use ‘-’ for each item, plain text, no markdown syntax."
  - trigger: ".timeline"
    replace: "Rewrite the text as a date-ordered list; each line starts with ‘- yyyy/mm/dd: event and content’, concise with no redundancy, one event per line."
  - trigger: ".bullet"
    replace: "Summarize the text in 2-level bullet points using ‘-’ only; nest related info when relevant, keep meaning, remove redundancy, and format all dates as yyyy/mm/dd."
  - trigger: ".tldr"
    replace: "Rewrite the text in under 100 words with concise, clear English that keeps the original meaning; remove redundancy, simplify structure, and format all dates as yyyy/mm/dd."
  - trigger: ".better"
    replace: "Write concise, consistent, active English using specific, concrete language; omit redundancies and organize ideas logically; convert all dates to yyyy/mm/dd."
  - trigger: ".appraise"
    replace: "To ULTRAthink, judging the trustworthiness, relevance, and clinical applicability of research, why an why not, pros and cons, Gather reliable evidence by WebSearch from peer-reviewed journals, reasoned evaluation"
  - trigger: ".addbib"
    replace: "做出以下的調整：根據的文章內容以及研究成果，以markdown pandoc風格 i.e.  [@Smith2024] 在文章中加入該引用，並在文章後加入引用列表，以 BibTex的格式 i.e. @article{Smith2024, ... 以 codebox 附在最後，請直接輸出在對話中。"
  - trigger: ".citation"
    replace: "做出以下的調整：根據的文章內容以及研究成果，以markdown風格 i.e. [1],[2-3] 在文章中加入該引用，並在文章後加入引用列表，以包含 DOI 的 APA 格式，請直接輸出在對話中。另外如果可以。以繁體中文的文法結構來寫每一個語句，人名請用台灣常用的翻釋人名，不用翻譯專有科學名詞"
  - trigger: ".comment"
    replace: "綜合地，(重要) 以哲學概念論述 (偏好當代 i.e. 20世紀後的哲學概念)、社會學、心理學的角度切入去探討，敘事性的評論式寫作、是在保持學理深度的同時允許帶有批判性視角和詮釋性的筆觸、較為延展的哲學性沉思，重點是長，學術地，長段落，有架構地，平靜、客觀，不煽情"
  - trigger: ".anime"
    replace: "這個作品，先從 fandom.com/wiki 或 wikipedia 了解這個作品 從 site: www.reddit.com OR site:https://forum.gamer.com.tw/  OR site:x.com  OR site:https://www.ptt.cc/  OR site:https://forums.animesuki.com/  OR site:https://myanimelist.net/ 來廣度優先地收集觀眾的感想與評論，了解大家在意的點，再綜合地，(重要) 以哲學概念論述 (偏好當代 i.e. 20世紀後的哲學概念)、社會學、心理學的角度切入去探討這個作品，包括角色塑造與認同、世界觀建構、議題探討，人名請用台灣常用的翻釋人名，敘事性的評論式寫作、是在保持學理深度的同時允許帶有批判性視角和詮釋性的筆觸、較為延展的哲學性沉思"
  - trigger: ".hy"
    replace: "highlight the high-yield oncology key points for board exams"
  - trigger: ".daily"
    replace: "請將以下資訊撰寫成 ASCO Daily News 風格的專業評論文章：明確定位讀者為腫瘤科臨床醫師與研究者。文章需包含五個部分： (1) 研究背景與臨床問題，簡要交代為何此研究重要；(2) 試驗設計與方法，包括研究類型、受試者人數、主要終點與隨訪；(3) 主要結果與數據摘要，需具體呈現關鍵數據（如 HR、CI、p 值）；(4) 專家評論，著重於臨床意涵、與既有標準治療的比較、以及對未來研究方向的啟發；(5) 研究限制與提醒，避免誇大。語氣需專業、精簡、臨床導向，避免浮誇字眼，兼顧資訊傳遞與批判性分析。"
  - trigger: ".pken"
    replace: "convert the context as Pocket Medicine styled text with nested list,  plain text, no markdown strong syntax, indent use 4 space, '- ' as the list marker, you can  use ↑↓ (for increase/decrease) →←Δ w/ w/o incl. ∵ ∴ ✔ (for check,approval) ✘ (no, not), ㊀ for negative, ㊉ for positive, these symbol or abbr for shortening line, adj. for adjuvant, s/p for after, return result in a codebox"
  - trigger: ".pkzh"
    replace: "convert the context as Pocket Medicine styled text with nested list,  plain text, no markdown strong syntax, indent use 4 space, '- ' as the list marker, you can  use ↑↓ (for increase/decrease) →←Δ w/ w/o incl. ∵ ∴ ✔ (for check,approval) ✘ (no, not), ㊀ for negative, ㊉ for positive, these symbol or abbr for shortening line, adj. for adjuvant, s/p for after, return result in a codebox, 以繁體中文的文法結構來寫每一個語句，但不用翻譯專有名詞，以維持符合台灣醫師習慣的可讀性"
  - trigger: ".zhtw"
    replace: "以繁體中文的文法結構來書寫或翻譯改寫原文的內容，但不翻譯專有名詞。以所謂醫療晶晶體，以維持符合台灣醫師習慣的可讀性"
  - trigger: ".solve"
    replace: "對每個選項解題，為什麼錯？為什麼對？以繁體中文的文法結構來書寫內容，但不翻譯專有名詞。以所謂醫療晶晶體，以維持符合台灣醫師習慣的可讀性"
  - trigger: ".onclearn"
    replace: "建立癌症治療學習摘要：依分期(早期/局部進展/轉移)整理不同的治療策略，梳理 landmark trials（年份、名稱、設計、病人群族、結果、臨床意義 e.g. 一線、二線等），進一步比較常混淆試驗，轉化為臨床決策要點，提供一個情況→策略的治療架構，並說明基於的證據。最後，列出五個學習重點，並加入數字/關鍵詞/時間軸的記憶技巧。以繁體中文的文法結構來寫每一個語句，但不用翻譯專有名詞，以維持符合台灣醫師習慣的可讀性"
  - trigger: ".top"
    replace: "Summarize this progress note into exactly 3 lines, 1st line: the oncology styled diagnose, 2nd line: reason for admission, 3rd line: current status,  Use html tag <BR> literally for line breaks, add a → at begining of each line, use as much abbr as possible (this is for a hand-off, so be concise), in English, return the final result in a codebox"
  - trigger: ".first.med"
    replace: " 請用第一性原理的方式解釋這個概念或疾病：1. 從核心機制（mechanism）出發，說明基本原理或病理；2. 以因果鏈（器官→功能→病理→臨床表現→治療）串連；3. 加入歷史時空背景或人名背景，用故事化呈現；4. 壓縮成模式或對照組（如過多 vs 不足，UMN vs LMN）；5. 用日常類比說明抽象概念；6. 最後比較與其他相關疾病/概念的異同。以繁體中文的文法結構來寫每一個語句，但不用翻譯專有名詞，以維持符合台灣醫師習慣的可讀性"
  - trigger: ".first.all"
    replace: " 請用第一性原理的方式解釋這個概念：1. 從核心機制（mechanism）出發，說明基本原理；2. 以因果鏈連接；3. 加入歷史時空背景或人名背景，用故事化呈現；4. 壓縮成模式或對照；5. 用日常類比說明抽象概念；6. 最後比較與其他相關概念的異同。以繁體中文的文法結構來寫每一個語句，但不用翻譯專有名詞，以維持符合台灣醫師習慣的可讀性"
  - trigger: ".NHI"
    replace: "請將我所提供的臨床病史、文件，改寫為符合臺灣行政機關（特別是健保署藥品事前審查文件）格式之正式公文語體。從病人臨床病史開始摘要，語氣須莊重、精確、尊敬且中性，避免口語或情緒化表達。適度運用「擬」、「爰以」、「爰為」、「茲檢陳」、「敬請」、「敬陳」、「敬復」、「鈞核」、「鈞示」、「俾利」、「以資」等常見公文詞彙，並調整句式，使其符合公文邏輯（先述事由、再敘理由、後陳請求）。保留原文資訊內容與醫療專業名詞，但改以官式文體呈現，字句應具備行政文書慣用之尊敬層級與條理結構。請精簡摘要，重點在因果跟邏輯，目標是據理力爭，獲得藥物申請核可。限一個段落，300字以內說明完成，以「病人xx歲女性/男性...」為開頭"
  - trigger: "interview"
    replace: "請幫我設計幾個腫瘤專科口試的一系列高階問答題，以及建議的答案，目標是這個考生有沒有了解這個病人， 這些問題的設計目的，是要測試考生是否理解臨床決策邏輯、藥物選擇依據、毒性處理原則與後線策略。每個問題後附「考官觀察重點」，幫助引導評估答題品質。以確定具備臨床整合與 guideline-based decision-making 能力"
  - trigger: "#blue"
    replace: "#3D6869"
  - trigger: "ymd"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%Y-%m-%d"
  - trigger: "mmdd"
    replace: "({{mydate}})"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m-%d"
  - trigger: "bitly"
    replace: "bit.ly/"
  # Shell commands
  - trigger: ":shelltest"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
  - trigger: "ft1"
    replace: "†"
  - trigger: "ft2"
    replace: "††"
  - trigger: "ft3"
    replace: "¶"
  - trigger: "ft4"
    replace: "§"
