local ls = require("luasnip")
-- some shorthands...
local s = ls.snippet
local t = ls.text_node
local i = ls.insert_node

return {
  s("Taz", { t("piperacillin/tazobactam") }),
  s("rx", { t("treatment") }),
  s("mgmt", { t("management") }),
  s("LN", { t("lymph node") }),
  s("mets", { t("metastasis") }),
  s("htn", { t("hypertension") }),
  -- Pocket medicine 8e --
  s("5′-NT", { t("5′-nucleotidase") }),
  s("6-MP", { t("6-mercaptopurine") }),
  s("AAA", { t("abdominal aortic aneurysm") }),
  s("AAD", { t("antiarrhythmic drug") }),
  s("Ab", { t("antibody") }),
  s("ABE", { t("acute bacterial endocarditis") }),
  s("ABG", { t("arterial blood gas") }),
  s("abnl", { t("abnormal") }),
  s("ABPA", { t("allergic bronchopulmonary aspergillosis") }),
  s("abx", { t("antibiotics") }),
  s("a/c", { t("anticoagulation") }),
  s("AC", { t("assist control") }),
  s("ACE", { t("angiotensin-converting enzyme") }),
  s("ACEI", { t("ACE inhibitor") }),
  s("ACI", { t("anemia of chronic inflammation") }),
  s("ACL", { t("anticardiolipin antibody") }),
  s("ACLS", { t("advanced cardiac life support") }),
  s("ACS", { t("acute coronary syndrome") }),
  s("ACTH", { t("adrenocorticotrophic hormone") }),
  s("ACV", { t("acyclovir") }),
  s("ADA", { t("adenosine deaminase") }),
  s("ADH", { t("antidiuretic hormone") }),
  s("ADL", { t("activities of daily living") }),
  s("AF", { t("atrial fibrillation") }),
  s("AFB", { t("acid-fast bacilli") }),
  s("AFL", { t("atrial flutter") }),
  s("AFP", { t("α-fetoprotein") }),
  s("AFTP", { t("ascites fluid total protein") }),
  s("AG", { t("aminoglycoside anion gap") }),
  s("Ag", { t("antigen") }),
  s("AGN", { t("acute glomerulonephritis") }),
  s("AI", { t("adrenal insufficiency") }),
  s("aortic insufficiency", { t("aortic insufficiency") }),
  s("aromatase inhibitor", { t("aromatase inhibitor") }),
  s("AIDS", { t("acquired immunodeficiency syndrome") }),
  s("AIH", { t("autoimmune hepatitis") }),
  s("AIHA", { t("autoimmune hemolytic anemia") }),
  s("AIN", { t("acute interstitial nephritis") }),
  s("AIP", { t("acute interstitial pneumonia") }),
  s("AKI", { t("acute kidney injury") }),
  s("ALF", { t("acute liver failure") }),
  s("ALL", { t("acute lymphoblastic leukemia") }),
  s("ALS", { t("amyotrophic lateral sclerosis") }),
  s("ALT", { t("alanine aminotransferase") }),
  s("AMA", { t("anti-mitochondrial antibody") }),
  s("AMI", { t("anterior myocardial infarction") }),
  s("AML", { t("acute myelogenous leukemia") }),
  s("amy", { t("amylase") }),
  s("ANA", { t("antinuclear antibody") }),
  s("ANCA", { t("antineutrophilic cytoplasmic Ab") }),
  s("AoD", { t("aortic dissection") }),
  s("AoV", { t("aortic valve") }),
  s("APAP", { t("acetyl-para-aminophenol") }),
  s("APC", { t("activated protein C") }),
  s("APL", { t("acute promyelocytic leukemia") }),
  s("APLA", { t("antiphospholipid Ab") }),
  s("APS", { t("antiphospholipid Ab synd.") }),
  s("ARB", { t("angiotensin receptor blocker") }),
  s("ARDS", { t("acute respiratory distress syndrome") }),
  s("ARV", { t("antiretroviral") }),
  s("ARVC", { t("arrhythmogenic RV CMP") }),
  s("AS", { t("aortic stenosis") }),
  s("ASA", { t("aspirin") }),
  s("ASD", { t("atrial septal defect") }),
  s("AST", { t("aspartate aminotransferase") }),
  s("asx", { t("asymptomatic") }),
  s("AT", { t("atrial tachycardia") }),
  s("ATII", { t("angiotensin II") }),
  s("ATIII", { t("antithrombin III") }),
  s("ATN", { t("acute tubular necrosis") }),
  s("ATRA", { t("all-trans-retinoic acid") }),
  s("AV", { t("atrioventricular") }),
  s("AVA", { t("aortic valve area") }),
  s("AVB", { t("atrioventricular block") }),
  s("AVNRT", { t("AV nodal reentrant tachycardia") }),
  s("AVR", { t("aortic valve replacement") }),
  s("AVRT", { t("AV reciprocating tachycardia") }),
  s("a/w", { t("associated with") }),
  s("AZA", { t("azathioprine") }),
  s("Aϕ", { t("alkaline phosphatase") }),
  s("BAL", { t("bronchoalveolar lavage") }),
  s("βB", { t("beta-blocker") }),
  s("BBB", { t("bundle branch block") }),
  s("b/c", { t("because") }),
  s("BCx", { t("blood culture") }),
  s("BD", { t("bile duct") }),
  s("BDZ", { t("benzodiazepines") }),
  s("bili.", { t("bilirubin") }),
  s("BiPAP", { t("bilevel positive airway pressure") }),
  s("BiV", { t("biventricular") }),
  s("BM", { t("bone marrow") }),
  s("bowel movement", { t("bowel movement") }),
  s("BMD", { t("bone mineral density") }),
  s("BMI", { t("body mass index") }),
  s("BMS", { t("bare metal stent") }),
  s("BNP", { t("B-type natriuretic peptide") }),
  s("BP", { t("blood pressure") }),
  s("BPH", { t("benign prostatic hypertrophy") }),
  s("BRBPR", { t("bright red blood per rectum") }),
  s("BS", { t("breath sounds") }),
  s("BT", { t("bleeding time") }),
  s("BUN", { t("blood urea nitrogen") }),
  s("bx", { t("biopsy") }),
  s("BYCE", { t("buffered charcoal yeast extract") }),
  s("C′", { t("complement") }),
  s("CABG", { t("coronary artery bypass grafting") }),
  s("CAD", { t("coronary artery disease") }),
  s("CAH", { t("congenital adrenal hyperplasia") }),
  s("CALLA", { t("common ALL antigen") }),
  s("CAPD", { t("chronic ambulatory peritoneal dialysis") }),
  s("CBC", { t("complete blood count") }),
  s("CBD", { t("common bile duct") }),
  s("CCB", { t("calcium channel blocker") }),
  s("CCl4", { t("carbon tetrachloride") }),
  s("CCP", { t("cyclic citrullinated peptide") }),
  s("CCS", { t("Canadian Cardiovascular Society") }),
  s("CCY", { t("cholecystectomy") }),
  s("CD", { t("Crohn’s disease") }),
  s("CEA", { t("carcinoembryonic antigen") }),
  s("CEA", { t("carotid endarterectomy") }),
  s("ceph.", { t("cephalosporin") }),
  s("c/f", { t("concern for") }),
  s("CF", { t("cystic fibrosis") }),
  s("CFU", { t("colony forming units") }),
  s("CHB", { t("complete heart block") }),
  s("CHD", { t("congenital heart disease") }),
  s("CHF", { t("congestive heart failure") }),
  s("CI", { t("cardiac index") }),
  s("CIAKI", { t("contrast-induced AKI") }),
  s("CIDP", { t("chronic inflammatory demyelinating polyneuropathy") }),
  s("CJD", { t("Creutzfeldt-Jakob disease") }),
  s("CK", { t("creatine kinase") }),
  s("CKD", { t("chronic kidney disease") }),
  s("CLL", { t("chronic lymphocytic leukemia") }),
  s("CMC", { t("carpometacarpal (joint)") }),
  s("CML", { t("chronic myelogenous leukemia") }),
  s("CMML", { t("chronic myelomonocytic leukemia") }),
  s("CMP", { t("cardiomyopathy") }),
  s("CMV", { t("cytomegalovirus") }),
  s("CN", { t("cranial nerve") }),
  s("CNI", { t("calcineurin inhibitor") }),
  s("CNS", { t("central nervous system") }),
  s("COP", { t("cryptogenic organizing PNA") }),
  s("COPD", { t("chronic obstructive pulm. dis.") }),
  s("COX", { t("cyclo-oxygenase") }),
  s("CP", { t("chest pain") }),
  s("CPAP", { t("continuous positive airway pressure") }),
  s("CPP", { t("cerebral perfusion pressure") }),
  s("CPPD", { t("calcium pyrophosphate dihydrate") }),
  s("Cr", { t("creatinine") }),
  s("CrAg", { t("cryptococcal antigen") }),
  s("CRC", { t("colorectal cancer") }),
  s("CrCl", { t("creatinine clearance") }),
  s("CRP", { t("C-reactive protein") }),
  s("CRT", { t("cardiac resynchronization therapy") }),
  s("c/s", { t("consult") }),
  s("CsA", { t("cyclosporine A") }),
  s("CSF", { t("cerebrospinal fluid") }),
  s("CSM", { t("carotid sinus massage") }),
  s("CT", { t("computed tomogram") }),
  s("CTA", { t("CT angiogram") }),
  s("CTD", { t("connective tissue disease") }),
  s("CTX", { t("ceftriaxone") }),
  s("CV", { t("cardiovascular") }),
  s("CVA", { t("cerebrovascular accident") }),
  s("CVD", { t("cerebrovascular disease") }),
  s("common variable immunodefic.", {}),
  s("CVP", { t("central venous pressure") }),
  s("CVVH", { t("continuous veno-venous hemofiltration") }),
  s("c/w", { t("compared with") }),
  s("CW", { t("chest wall") }),
  s("cx", { t("culture") }),
  s("CXR", { t("chest radiograph") }),
  s("CYC", { t("cyclophosphamide") }),
  s("d", { t("day") }),
  s("D", { t("death") }),
  s("ΔMS", { t("change in mental status") }),
  s("DA", { t("dopamine") }),
  s("DAD", { t("diffuse alveolar damage") }),
  s("DAH", { t("diffuse alveolar hemorrhage") }),
  s("DAT", { t("direct antiglobulin test") }),
  s("DBP", { t("diastolic blood pressure") }),
  s("d/c", { t("discharge") }),
  s("dc", { t("discontinue") }),
  s("DCIS", { t("ductal carcinoma in situ") }),
  s("DCMP", { t("dilated cardiomyopathy") }),
  s("DCT", { t("distal collecting tubule") }),
  s("Ddx", { t("differential diagnosis") }),
  s("DES", { t("drug-eluting stent") }),
  s("DFA", { t("direct fluorescent antigen detection") }),
  s("DI", { t("diabetes insipidus") }),
  s("DIC", { t("disseminated intravascular coagulation") }),
  s("diff.", { t("differential") }),
  s("DIP", { t("desquamative interstitial pneumonitis") }),
  s("DKA", { t("diabetic ketoacidosis") }),
  s("DLCO", { t("diffusion capacity of the lung") }),
  s("DLE", { t("drug-induced lupus") }),
  s("DM", { t("diabetes mellitus") }),
  s("DMARD", { t("disease-modifying anti-rheumatic drug") }),
  s("DOE", { t("dyspnea on exertion") }),
  s("DRE", { t("digital rectal exam") }),
  s("DRESS", { t("drug reaction w/ eosinophilia & systemic symptoms") }),
  s("DSE", { t("dobutamine stress echo") }),
  s("DST", { t("dexamethasone suppression test") }),
  s("DTRs", { t("deep tendon reflexes") }),
  s("DU", { t("duodenal ulcer") }),
  s("DVT", { t("deep vein thrombosis") }),
  s("dx", { t("diagnosis") }),
  s("EAD", { t("extreme axis deviation") }),
  s("EAV", { t("effective arterial volume") }),
  s("EBV", { t("Epstein-Barr virus") }),
  s("ECG", { t("electrocardiogram") }),
  s("ECMO", { t("extracorporeal membrane oxygenation") }),
  s("ED", { t("emergency department") }),
  s("EDP", { t("end-diastolic pressure") }),
  s("EDV", { t("end-diastolic volume") }),
  s("EEG", { t("electroencephalogram") }),
  s("EF", { t("ejection fraction") }),
  s("EGD", { t("esophagogastroduodenoscopy") }),
  s("EGFR", { t("epidermal growth factor receptor") }),
  s("EGPA", { t("eosinophilic granulomatosis with polyangiitis") }),
  s("EI", { t("entry inhibitor") }),
  s("EIA", { t("enzyme-linked immunoassay") }),
  s("ELISA", { t("enzyme-linked immunosorbent assay") }),
  s("EM", { t("electron microscopy") }),
  s("EMB", { t("ethambutol") }),
  s("ENaC", { t("epithelial Na channel") }),
  s("ENT", { t("ears, nose, & throat") }),
  s("e/o", { t("evidence of") }),
  s("EOM", { t("extraocular movement/muscles") }),
  s("EP", { t("electrophysiology") }),
  s("Epo", { t("erythropoietin") }),
  s("EPS", { t("electrophysiology study") }),
  s("ERCP", { t("endoscopic retrograde cholangiopancreatography") }),
  s("ERV", { t("expiratory reserve volume") }),
  s("ESA", { t("erythropoiesis-stimulating agents") }),
  s("ESBL", { t("extended spectrum beta-lactamase") }),
  s("ESP", { t("end-systolic pressure") }),
  s("ESR", { t("erythrocyte sedimentation rate") }),
  s("ESRD", { t("end-stage renal disease") }),
  s("ESV", { t("end-systolic volume") }),
  s("ET", { t("essential thrombocythemia") }),
  s("ETT", { t("endotracheal tube") }),
  s("EUS", { t("endoscopic ultrasound") }),
  s("FDP", { t("fibrin degradation product") }),
  s("FEV1", { t("forced expir. vol in 1 sec") }),
  s("FFP", { t("fresh frozen plasma") }),
  s("FHx", { t("family history") }),
  s("FI", { t("fusion inhibitor") }),
  s("FMD", { t("fibromuscular dysplasia") }),
  s("FMF", { t("familial Mediterranean fever") }),
  s("FNA", { t("fine-needle aspiration") }),
  s("FOB", { t("fecal occult blood") }),
  s("FOBT", { t("fecal occult blood testing") }),
  s("FQ", { t("fluoroquinolone") }),
  s("FRC", { t("functional residual capacity") }),
  s("FSGS", { t("focal segmental glomerulosclerosis") }),
  s("FSH", { t("follicle-stimulating hormone") }),
  s("FTI", { t("free thyroxine index") }),
  s("FUO", { t("fever of unknown origin") }),
  s("f/u", { t("follow-up") }),
  s("FVC", { t("forced vital capacity") }),
  s("G6PD", { t("glc-6-phosphate dehydrogenase") }),
  s("GB", { t("gallbladder") }),
  s("GBM", { t("glomerular basement membrane") }),
  s("GBS", { t("Guillain-Barré syndrome") }),
  s("GCA", { t("giant cell arteritis") }),
  s("GCS", { t("Glasgow coma scale") }),
  s("G-CSF", { t("granulocyte colony-stimulating factor") }),
  s("GE", { t("gastroesophageal") }),
  s("gen.", { t("generation") }),
  s("GERD", { t("gastroesophageal reflux disease") }),
  s("GFR", { t("glomerular filtration rate") }),
  s("GGT", { t("γ-glutamyl transpeptidase") }),
  s("GH", { t("growth hormone") }),
  s("GIB", { t("gastrointestinal bleed") }),
  s("GIST", { t("gastrointestinal stromal tumor") }),
  s("glc", { t("glucose") }),
  s("GMCSF", { t("granulocyte-macrophage colony-stimulating factor") }),
  s("GN", { t("glomerulonephritis") }),
  s("GNR", { t("gram-negative rods") }),
  s("GnRH", { t("gonadotropin-releasing hormone") }),
  s("GPA", { t("granulomatosis w/ polyangiitis") }),
  s("GPC", { t("gram-positive cocci") }),
  s("GPI", { t("glycoprotein IIb/IIIa inhibitor") }),
  s("GRA", { t("glucocorticoid-remediable aldosteronism") }),
  s("GU", { t("gastric ulcer") }),
  s("GVHD", { t("graft-versus-host disease") }),
  s("h", { t("hour") }),
  s("H2RA", { t("H2-receptor antagonist") }),
  s("HA", { t("headache") }),
  s("HACA", { t("human antichimeric antibody") }),
  s("HAV", { t("hepatitis A virus") }),
  s("Hb", { t("hemoglobin") }),
  s("HBIG", { t("hepatitis B immunoglobulin") }),
  s("HBV", { t("hepatitis B virus") }),
  s("HCC", { t("hepatocellular carcinoma") }),
  s("HCMP", { t("hypertrophic cardiomyopathy") }),
  s("Hct", { t("hematocrit") }),
  s("HCV", { t("hepatitis C virus") }),
  s("HCW", { t("health care worker") }),
  s("HD", { t("hemodialysis") }),
  s("HDL", { t("high-density lipoprotein") }),
  s("HDV", { t("hepatitis D virus") }),
  s("HELLP", { t("hemolysis, abnl LFTs, low plts") }),
  s("HEV", { t("hepatitis E virus") }),
  s("HF", { t("heart failure") }),
  s("HGPRT", { t("hypoxanthine-guanine phosphoribosyl transferase") }),
  s("HHS", { t("hyperosmolar hyperglycemic state") }),
  s("HIT", { t("heparin-induced thrombocytopenia") }),
  s("HK", { t("hypokinesis") }),
  s("HL", { t("Hodgkin lymphoma") }),
  s("h/o", { t("history of") }),
  s("HOB", { t("head of bed") }),
  s("HoTN", { t("hypotension") }),
  s("hpf", { t("high-power field") }),
  s("HPT", { t("hyperparathyroidism") }),
  s("HR", { t("heart rate") }),
  s("HRT", { t("hormone replacement therapy") }),
  s("HS", { t("hereditary spherocytosis") }),
  s("HSCT", { t("hematopoietic stem cell transplantation") }),
  s("HSM", { t("hepatosplenomegaly") }),
  s("HSP", { t("Henoch-Schönlein purpura") }),
  s("HSV", { t("herpes simplex virus") }),
  s("HTN", { t("hypertension") }),
  s("HUS", { t("hemolytic uremic syndrome") }),
  s("hx", { t("history") }),
  s("I&D", { t("incision & drainage") }),
  s("IABP", { t("intra-aortic balloon pump") }),
  s("IBD", { t("inflammatory bowel disease") }),
  s("IBS", { t("irritable bowel syndrome") }),
  s("IC", { t("inspiratory capacity") }),
  s("ICa", { t("ionized calcium") }),
  s("ICD", { t("implantable cardiac defibrillator") }),
  s("ICH", { t("intracranial hemorrhage") }),
  s("ICP", { t("intracranial pressure") }),
  s("ICU", { t("intensive care unit") }),
  s("IE", { t("infective endocarditis") }),
  s("IGF", { t("insulin-like growth factor") }),
  s("IGRA", { t("interferon-γ release assay") }),
  s("II", { t("integrase inhibitor") }),
  s("IIP", { t("idiopathic interstitial PNA") }),
  s("ILD", { t("interstitial lung disease") }),
  s("IMI", { t("inferior myocardial infarction") }),
  s("infxn", { t("infection") }),
  s("inh", { t("inhaled") }),
  s("INH", { t("isoniazid") }),
  s("INR", { t("international normalized ratio") }),
  s("IPAA", { t("ileal pouch-anal anastomosis") }),
  s("IPF", { t("idiopathic pulmonary fibrosis") }),
  s("ITP", { t("idiopathic thrombocytopenic purpura") }),
  s("IVB", { t("intravenous bolus") }),
  s("IVC", { t("inferior vena cava") }),
  s("IVDU", { t("intravenous drug use(r)") }),
  s("IVF", { t("intravenous fluids") }),
  s("IVIg", { t("intravenous immunoglobulin") }),
  s("JVD", { t("jugular venous distention") }),
  s("JVP", { t("jugular venous pulse") }),
  s("KS", { t("Kaposi’s sarcoma") }),
  s("KUB", { t("kidney-ureter-bladder (radiography)") }),
  s("LA", { t("left atrium"), t("long-acting") }),
  s("LA", { t("lupus anticoagulant") }),
  s("LBBB", { t("left bundle branch block") }),
  s("LCA", { t("left coronary artery") }),
  s("LCIS", { t("lobular carcinoma in situ") }),
  s("LCx", { t("left circumflex cor. art.") }),
  s("LDH", { t("lactate dehydrogenase") }),
  s("LDL", { t("low-density lipoprotein") }),
  s("LE", { t("lower extremity") }),
  s("LES", { t("lower esophageal sphincter") }),
  s("LFTs", { t("liver function tests") }),
  s("LGIB", { t("lower gastrointestinal bleed") }),
  s("LGV", { t("lymphogranuloma venereum") }),
  s("LH", { t("luteinizing hormone") }),
  s("LLQ", { t("left lower quadrant") }),
  s("LM", { t("left main coronary artery") }),
  s("LMWH", { t("low-molecular-weight heparin") }),
  s("LN", { t("lymph node") }),
  s("LOC", { t("loss of consciousness") }),
  s("LOS", { t("length of stay") }),
  s("LP", { t("lumbar puncture") }),
  s("lpf", { t("low-power field") }),
  s("LQTS", { t("long QT syndrome") }),
  s("LR", { t("lactated Ringer’s") }),
  s("LUSB", { t("left upper sternal border") }),
  s("LV", { t("left ventricle") }),
  s("LVAD", { t("LV assist device") }),
  s("LVEDP", { t("LV end-diastolic pressure") }),
  s("LVEDV", { t("LV end-diastolic volume") }),
  s("LVESD", { t("LV end-systolic diameter") }),
  s("LVH", { t("left ventricular hypertrophy") }),
  s("LVOT", { t("left ventricular outflow tract") }),
  s("LVSD", { t("LV systolic dimension") }),
  s("mAb", { t("monoclonal antibody") }),
  s("MAC", { t("Mycobacterium avium complex") }),
  s("MAHA", { t("microangiopathic hemolytic anemia") }),
  s("MALT", { t("mucosa-assoc. lymphoid tissue") }),
  s("MAO", { t("monoamine oxidase") }),
  s("MAP", { t("mean arterial pressure") }),
  s("MAT", { t("multifocal atrial tachycardia") }),
  s("MCD", { t("minimal change disease") }),
  s("MCP", { t("metacarpal phalangeal (joint)") }),
  s("MCS", { t("mechanical circulatory support") }),
  s("MCTD", { t("mixed connective tissue dis.") }),
  s("MCV", { t("mean corpuscular volume") }),
  s("MDI", { t("metered dose inhaler") }),
  s("MDMA", { t("3,4-methylenedioxymetham- phetamine (Ecstasy)") }),
  s("MDR", { t("multidrug resistant") }),
  s("MDS", { t("myelodysplastic syndrome") }),
  s("MEN", { t("multiple endocrine neoplasia") }),
  s("MG", { t("myasthenia gravis") }),
  s("MGUS", { t("monoclonal gammopathy of uncertain significance") }),
  s("MI", { t("myocardial infarction") }),
  s("min", { t("minute") }),
  s("min.", { t("minimal") }),
  s("MM", { t("multiple myeloma") }),
  s("MMEFR", { t("max. mid-expir. flow rate") }),
  s("MMF", { t("mycophenolate mofetil") }),
  s("MN", { t("membranous nephropathy") }),
  s("MNZ", { t("metronidazole") }),
  s("mo", { t("month") }),
  s("mod.", { t("moderate") }),
  s("MODS", { t("multiple organ dysfxn synd.") }),
  s("MPA", { t("microscopic polyangiitis") }),
  s("MPGN", { t("membranoproliferative glomerulonephritis") }),
  s("MPN", { t("myeloproliferative neoplasm") }),
  s("MR", { t("mitral regurgitation") }),
  s("MRA", { t("magnetic resonance angiography") }),
  s("MRCP", { t("MR cholangiopancreatography") }),
  s("MRI", { t("magnetic resonance imaging") }),
  s("MRSA", { t("methicillin-resistant S. aureus") }),
  s("MS", { t("mitral stenosis") }),
  s("MSA", { t("multisystem atrophy") }),
  s("MSK", { t("musculoskeletal") }),
  s("MTb", { t("Mycobacterium tuberculosis") }),
  s("mTOR", { t("mechanistic target of rapamycin") }),
  s("MTP", { t("metatarsal phalangeal (joint)") }),
  s("MTX", { t("methotrexate") }),
  s("MV", { t("mitral valve") }),
  s("MVA", { t("mitral valve area") }),
  s("MVP", { t("mitral valve prolapse") }),
  s("MVR", { t("mitral valve replacement") }),
  s("NAC", { t("N-acetylcysteine") }),
  s("NAFLD", { t("non-alcoholic fatty liver disease") }),
  s("NASH", { t("non-alcoholic steatohepatitis") }),
  s("NG", { t("nasogastric") }),
  s("NGT", { t("nasogastric tube") }),
  s("NHL", { t("non-Hodgkin lymphoma") }),
  s("niCMP", { t("non-ischemic CMP") }),
  s("NIF", { t("negative inspiratory force") }),
  s("NJ", { t("nasojejunal") }),
  s("nl", { t("normal") }),
  s("NM", { t("neuromuscular") }),
  s("NMJ", { t("neuromuscular junction") }),
  s("NNRTI", { t("non-nucleoside reverse transcriptase inhibitor") }),
  s("PVD", { t("peripheral vascular disease") }),
  s("PVE", { t("prosthetic valve endocarditis") }),
  s("CPS", { t("PD-L1 Combined Positive Score (CPS)"), i(0) }),
  s("PVR", { t("pulmonary vascular resistance") }),
  s("PZA", { t("pyrazinamide") }),
  s("qac", { t("before every meal") }),
  s("qhs", { t("every bedtime") }),
  s("QoL", { t("quality of life") }),
  s("Qw", { t("Q wave") }),
  s("RA", { t("rheumatoid arthritis") }),
  s("RAA", { t("renin-angiotensin-aldosterone") }),
  s("RAD", { t("right axis deviation") }),
  s("RAE", { t("right atrial enlargement") }),
  s("RAI", { t("radioactive iodine") }),
  s("RAIU", { t("radioactive iodine uptake") }),
  s("RAS", { t("renal artery stenosis") }),
  s("RAST", { t("radioallergosorbent test") }),
  s("RBBB", { t("right bundle branch block") }),
  s("RBC", { t("red blood cell") }),
  s("RBF", { t("renal blood flow") }),
  s("RBV", { t("ribavirin") }),
  s("RCA", { t("right coronary artery") }),
  s("RCMP", { t("restrictive cardiomyopathy") }),
  s("RCT", { t("randomized controlled trial") }),
  s("RDW", { t("red cell distribution width") }),
  s("RE", { t("reticuloendothelial") }),
  s("RF", { t("risk factor") }),
  s("RFA", { t("radiofrequency ablation") }),
  s("RHD", { t("rheumatic heart disease") }),
  s("r/i", { t("rule in") }),
  s("RI", { t("reticulocyte index") }),
  s("RIBA", { t("recombinant immunoblot assay") }),
  s("RMSF", { t("Rocky Mountain spotted fever") }),
  s("r/o", { t("rule out") }),
  s("ROS", { t("review of systems") }),
  s("RPGN", { t("rapidly progressive glomerulonephritis") }),
  s("RR", { t("respiratory rate") }),
  s("RRT", { t("renal replacement therapy") }),
  s("RT", { t("radiation therapy") }),
  s("RTA", { t("renal tubular acidosis") }),
  s("RTX", { t("rituximab") }),
  s("RUQ", { t("right upper quadrant") }),
  s("RUSB", { t("right upper sternal border") }),
  s("RV", { t("residual volume") }),
  s("RVAD", { t("RV assist device") }),
  s("RVH", { t("right ventricular hypertrophy") }),
  s("RVOT", { t("RV outflow tract") }),
  s("RVSP", { t("RV systolic pressure") }),
  s("Rx", { t("therapy") }),
  s("RYGB", { t("roux-en-Y gastric bypass") }),
  s("SA", { t("sinoatrial") }),
  s("SAAG", { t("serum-ascites albumin gradient") }),
  s("SAH", { t("subarachnoid hemorrhage") }),
  s("SB", { t("small bowel") }),
  s("SBE", { t("subacute bacterial endocarditis") }),
  s("SBO", { t("small bowel obstruction") }),
  s("SBP", { t("spontaneous bacterial peritoni") }),
  s("SBT", { t("spontaneous breathing trial") }),
  s("SC", { t("subcutaneous") }),
  s("SCD", { t("sudden cardiac death") }),
  s("SCID", { t("severe combined immunodefic.") }),
  s("SCLC", { t("small-cell lung cancer") }),
  s("s/e", { t("side effect") }),
  s("Se", { t("sensitivity") }),
  s("sec", { t("second") }),
  s("SERM", { t("selective estrogen receptor modulator") }),
  s("sev.", { t("severe") }),
  s("SHBG", { t("steroid hormone binding globulin") }),
  s("SIADH", { t("synd. of inappropriate ADH") }),
  s("SIBO", { t("small intestine bacterial overgrowth") }),
  s("SIEP", { t("serum immunoelectrophoresis") }),
  s("SIHD", { t("stable ischemic heart disease") }),
  s("SIMV", { t("synchronized intermittent mandatory ventilation") }),
  s("SIRS", { t("systemic inflammatory response syndrome") }),
  s("SJS", { t("Stevens-Johnson syndrome") }),
  s("SLE", { t("systemic lupus erythematosus") }),
  s("SMA", { t("superior mesenteric artery") }),
  s("SMV", { t("superior mesenteric vein") }),
  s("SMX", { t("sulfamethoxazole") }),
  s("SOS", { t("sinusoidal obstructive synd.") }),
  s("s/p", { t("status post") }),
  s("Sp", { t("specificity") }),
  s("SPEP", { t("serum protein electrophoresis") }),
  s("SR", { t("sinus rhythm") }),
  s("s/s", { t("signs and symptoms") }),
  s("SSCY", { t("Salmonella, Shigella, Campylobacter, Yersinia") }),
  s("SSRI", { t("selective serotonin reuptake inhibitor") }),
  s("SSS", { t("sick sinus syndrome") }),
  s("SSZ", { t("sulfasalazine") }),
  s("ST", { t("sinus tachycardia") }),
  s("STD", { t("ST-segment depression") }),
  s("STE", { t("ST-segment elevation") }),
  s("STI", { t("sexually transmitted infection") }),
  s("SV", { t("stroke volume") }),
  s("SVC", { t("superior vena cava") }),
  s("SVR", { t("systemic vascular resistance") }),
  s("SVT", { t("supraventricular tachycardia") }),
  s("sx", { t("symptom(s) or symptomatic") }),
  s("T1D", { t("type 1 diabetes mellitus") }),
  s("T2D", { t("type 2 diabetes mellitus") }),
  s("T3RU", { t("T3 resin uptake") }),
  s("TAA", { t("thoracic aortic aneurysm") }),
  s("TAVI", { t("transcatheter aortic valve implantation") }),
  s("TB", { t("tuberculosis") }),
  s("TBG", { t("thyroid binding globulin") }),
  s("TCA", { t("tricyclic antidepressant") }),
  s("TCD", { t("transcranial Doppler") }),
  s("TCN", { t("tetracycline") }),
  s("Tdap", { t("tetanus, diphtheria, pertussis") }),
  s("TdP", { t("torsades de pointes") }),
  s("TdT", { t("terminal deoxynucleotidyl transferase") }),
  s("TEE", { t("transesophageal echo") }),
  s("tfn", { t("transfusion") }),
  s("TFTs", { t("thyroid function tests") }),
  s("TG", { t("triglycerides") }),
  s("TGA", { t("transposition of the great arteries") }),
  s("TIA", { t("transient ischemic attack") }),
  s("TIBC", { t("total iron binding capacity") }),
  s("TINU", { t("tubulointerstitial nephritis and uveitis") }),
  s("TIPS", { t("transjugular intrahepatic portosystemic shunt") }),
  s("TKI", { t("tyrosine kinase inhibitor") }),
  s("TLC", { t("total lung capacity") }),
  s("TLS", { t("tumor lysis syndrome") }),
  s("TMP", { t("trimethoprim") }),
  s("Tn", { t("troponin") }),
  s("TP", { t("total protein") }),
  s("TPMT", { t("thiopurine methyltransferase") }),
  s("TPN", { t("total parenteral nutrition") }),
  s("Tpo", { t("thrombopoietin") }),
  s("TPO", { t("thyroid peroxidase") }),
  s("TR", { t("tricuspid regurgitation") }),
  s("TRALI", { t("transfusion-related acute lung injury") }),
  s("TRH", { t("thyrotropin-releasing hormone") }),
  s("TRS", { t("TIMI risk score") }),
  s("TRUS", { t("transrectal ultrasound") }),
  s("TS", { t("tricuspid stenosis") }),
  s("TSH", { t("thyroid-stimulating hormone") }),
  s("TSI", { t("thyroid-stimulating immunoglobulin") }),
  s("TSS", { t("toxic shock syndrome") }),
  s("TTE", { t("transthoracic echocardiogram") }),
  s("TTKG", { t("transtubular potassium gradient") }),
  s("TTP", { t("thrombotic thrombocytopenic purpura") }),
  s("TV", { t("tricuspid valve") }),
  s("Tw", { t("T wave") }),
  s("TWF", { t("T-wave flattening") }),
  s("TWI", { t("T-wave inversion") }),
  s("Tx", { t("transplant") }),
  s("TZD", { t("thiazolidinediones") }),
  s("U/A", { t("urinalysis") }),
  s("UA", { t("unstable angina") }),
  s("UAG", { t("urine anion gap") }),
  s("UC", { t("ulcerative colitis") }),
  s("UCx", { t("urine culture") }),
  s("UES", { t("upper esophageal sphincter") }),
  s("UFH", { t("unfractionated heparin") }),
  s("UGIB", { t("upper gastrointestinal bleed") }),
  s("UIP", { t("usual interstitial pneumonitis") }),
  s("ULN", { t("upper limit of normal") }),
  s("UOP", { t("urine output") }),
  s("UPEP", { t("urine protein electrophoresis") }),
  s("UR", { t("urgent revascularization") }),
  s("UrA", { t("uric acid") }),
  s("URI", { t("upper resp. tract infxn") }),
  s("U/S", { t("ultrasound") }),
  s("UTI", { t("urinary tract infection") }),
  s("V/Q", { t("ventilation-perfusion") }),
  s("VAD", { t("ventricular assist device") }),
  s("VAP", { t("ventilator-associated PNA") }),
  s("VATS", { t("video-assisted thoracoscopic surgery") }),
  s("VBI", { t("vertebrobasilar insufficiency") }),
  s("VC", { t("vital capacity") }),
  s("VD", { t("vessel disease") }),
  s("VDRL", { t("venereal disease research laboratory (test for syphilis)") }),
  s("VEGF", { t("vascular endothelial growth factor") }),
  s("VEXAS", { t("vacuoles, E1 enzyme, X-linked, autoinflammatory, somatic") }),
  s("VF", { t("ventricular fibrillation") }),
  s("VLDL", { t("very-low-density lipoproteins") }),
  s("VOD", { t("veno-occlusive disease") }),
  s("VS", { t("vital signs") }),
  s("VSD", { t("ventricular septal defect") }),
  s("Vt", { t("tidal volume") }),
  s("VT", { t("ventricular tachycardia") }),
  s("VTE", { t("venous thromboembolus") }),
  s("vWD", { t("von Willebrand’s disease") }),
  s("vWF", { t("von Willebrand’s factor") }),
  s("VZV", { t("varicella zoster virus") }),
  s("w/", { t("with") }),
  s("WBC", { t("white blood cell (count)") }),
  s("WCT", { t("wide-complex tachycardia") }),
  s("WHO", { t("World Health Organization") }),
  s("wk", { t("week") }),
  s("WM", { t("Waldenström’s macroglobulinemia") }),
  s("WMA", { t("wall motion abnormality") }),
  s("w/o", { t("without") }),
  s("WPW", { t("Wolff-Parkinson-White syndrome") }),
  s("w/u", { t("workup") }),
  s("XRT", { t("radiation therapy") }),
}
