#!/usr/bin/env python3
"""Generate a VHS .tape for an agent demo from a clean prompt list.

VHS has no functions/macros, so authoring word-by-word typing by hand is
verbose and error-prone. This generator emits the full tape — word-by-word
reveal, a read-pause before Enter, sentinel waits, and the per-agent quirks
(Codex multi-turn uses Sleeps, not Waits; startup settle for instant typing).

Usage:
  gen_tape.py --agent claude "first prompt" "second prompt" > demo.tape
  gen_tape.py --agent codex --theme light --scale 2 -o codex.tape "a prompt"

Then: vhs demo.tape
Requires the Stop hook staged in the demo dir (see references/setup.md).
"""

import argparse
import sys

THEMES = {"dark": "Catppuccin Mocha", "light": "Catppuccin Latte"}


def q(word):
    """Quote a word for VHS Type, picking a quote char it doesn't contain."""
    if '"' not in word:
        return f'"{word}"'
    if "'" not in word:
        return f"'{word}'"
    # contains both: fall back to double quotes with the inner ones stripped
    return '"' + word.replace('"', "") + '"'


def type_words(prompt, word_delay, read_pause):
    """Emit one `Type` per word (leading space joins), then the read-pause."""
    lines = []
    for i, word in enumerate(prompt.split()):
        token = word if i == 0 else " " + word
        lines.append(f"Type {q(token)}")
        lines.append(f"Sleep {word_delay}ms")
    # replace the trailing inter-word sleep with the read-pause before Enter
    lines[-1] = f"Sleep {read_pause}s"
    return lines


def main():
    p = argparse.ArgumentParser(description="Generate a VHS agent-demo tape.")
    p.add_argument("prompts", nargs="+", help="one quoted prompt per turn")
    p.add_argument("--agent", choices=["claude", "codex"], default="claude")
    p.add_argument(
        "--format",
        choices=["gif", "mp4", "webm"],
        default="gif",
        help="output format; mp4/webm feed the HTML video player",
    )
    p.add_argument("--theme", choices=["dark", "light"], default="dark")
    p.add_argument("--font-size", type=int, default=27)
    p.add_argument("--scale", type=int, default=1, help="DPI multiplier (2 = crisp)")
    p.add_argument(
        "--codex-type-speed",
        type=int,
        default=55,
        help="Codex smooth typing, ms/char (Codex can't do "
        "word-by-word under VHS — see below)",
    )
    p.add_argument(
        "--word-delay",
        type=int,
        default=220,
        help="ms between words (Claude word-by-word reveal)",
    )
    p.add_argument("--read-pause", type=int, default=3, help="s before Enter")
    p.add_argument("--answer-wait", type=int, default=120, help="s sentinel timeout")
    p.add_argument(
        "--codex-turn2-sleep",
        type=int,
        default=25,
        help="s to wait for Codex turn-2+ responses (no sentinel Wait)",
    )
    p.add_argument(
        "--codex-settle",
        type=int,
        default=8,
        help="s after Codex is ready before typing — lets late async "
        "startup notices (skills-budget warning) land first",
    )
    p.add_argument("-o", "--output", help="write to file instead of stdout")
    a = p.parse_args()

    font = a.font_size * a.scale
    width, height = 1600 * a.scale, 900 * a.scale
    out_gif = f"{a.agent}-demo.{a.format}"
    is_claude = a.agent == "claude"
    L = []  # tape lines

    # Typing strategy differs by agent:
    #  Claude — word-by-word: TypingSpeed 0 so each per-word `Type` pops in,
    #           paced by a Sleep between words.
    #  Codex  — smooth single `Type`: its composer treats the chunked bursts
    #           of word-by-word as a paste and then Enter won't submit, so we
    #           type the whole prompt at a steady ms/char instead.
    type_speed = 0 if is_claude else a.codex_type_speed
    speed_note = (
        "# Claude: word-by-word reveal (TypingSpeed 0 + per-word Sleep)"
        if is_claude
        else "# Codex: smooth typing (word-by-word breaks Codex submission)"
    )

    L += [
        f"# Auto-generated by gen_tape.py — edit prompts and regenerate.",
        f"# Render with: vhs <this file>",
        f"Output {out_gif}",
        "",
        f"Set FontSize {font}",
        f"Set Width {width}",
        f"Set Height {height}",
        f'Set Theme "{THEMES[a.theme]}"',
        speed_note,
        f"Set TypingSpeed {type_speed}ms",
        "",
        'Env VHS_DEMO "1"',
        "",
        "# Settle so the shell prompt is ready before typing",
        "Sleep 2s",
        f'Type "{a.agent}"',
        "Enter",
        "",
    ]

    if is_claude:
        L += [r"Wait+Screen@60s /shift\+tab|for shortcuts/", ""]
    else:
        # Wait for the READY status line (".. % left"), NOT the splash
        # (/model to change/): Codex accepts typed chars early but drops the
        # submit Enter until the TUI finishes loading, which is when the
        # status line appears.
        L += [r"Wait+Screen@60s /% left/", f"Sleep {a.codex_settle}s", ""]

    for turn, prompt in enumerate(a.prompts, start=1):
        L.append(f"# --- Turn {turn} ---")
        if turn >= 2:
            L.append("Sleep 3s")  # let the previous turn settle
        # typing
        if is_claude:
            L += type_words(prompt, a.word_delay, a.read_pause)
        else:
            L += [f"Type {q(prompt)}", f"Sleep {a.read_pause}s"]
        # submit: Codex/VHS drops Enter intermittently (any turn) — double-tap
        # guards it; the 2nd Enter is a no-op once the prompt has submitted.
        if is_claude:
            L.append("Enter")
        else:
            L += ["Enter", "Sleep 1s", "Enter"]
        # completion detection: sentinel Wait is reliable for Claude (all
        # turns) and Codex turn 1; Codex turn 2+ uses a plain Sleep (the Wait
        # polling disturbs Codex's rendering past turn 1).
        if not is_claude and turn >= 2:
            L.append(f"Sleep {a.codex_turn2_sleep}s")
        else:
            L.append(f"Wait+Screen@{a.answer_wait}s /VHS_TURN_DONE_{turn}/")
        L.append("")

    L += [
        "# Hold on the finished response, then quit",
        "Sleep 5s",
        "Ctrl+C",
        "Sleep 500ms",
        "Ctrl+C",
        "Sleep 1s",
        "",
    ]

    text = "\n".join(L)
    if a.output:
        with open(a.output, "w") as f:
            f.write(text)
        print(f"wrote {a.output}", file=sys.stderr)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
