# BookLore — Digital Library on VM
# EPUB, PDF, CBZ reader with auto-metadata
# Access: http://vm/booklore (via Traefik)
# Ref: https://github.com/booklore-app/booklore | https://booklore.org
#
# Crane images needed:
#   crane pull booklore/booklore:latest /tmp/booklore.tar
#   crane pull lscr.io/linuxserver/mariadb:latest /tmp/mariadb.tar
#
# Volume setup:
#   mkdir -p ~/docker/booklore/{data,books,bookdrop,db}
#
# Traefik: ~/traefik/dynamic/booklore.yml (already exists)
# Homepage: entry under "Media" group in ~/homepage/config/services.yaml

services:
  booklore:
    image: booklore/booklore:latest
    restart: unless-stopped
    # No host ports — Traefik routes /booklore via traefik-proxy network
    volumes:
      - /home/htlin222/docker/booklore/data:/app/data
      - /home/htlin222/docker/booklore/books:/books
      - /home/htlin222/docker/booklore/bookdrop:/bookdrop
    environment:
      USER_ID: 1000
      GROUP_ID: 1000
      TZ: Asia/Taipei
      DATABASE_URL: jdbc:mariadb://db:3306/booklore
      DATABASE_USERNAME: booklore
      DATABASE_PASSWORD: changeme
    depends_on:
      db:
        condition: service_healthy
    networks:
      - traefik-proxy

  db:
    image: lscr.io/linuxserver/mariadb:latest
    restart: unless-stopped
    volumes:
      - /home/htlin222/docker/booklore/db:/config
    environment:
      MYSQL_ROOT_PASSWORD: changeme-root
      MYSQL_DATABASE: booklore
      MYSQL_USER: booklore
      MYSQL_PASSWORD: changeme
    healthcheck:
      test: ["CMD-SHELL", "mariadb -u booklore -p'changeme' -e 'SELECT 1' 2>/dev/null"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true

# Drop EPUB/PDF/CBZ files into ~/docker/booklore/bookdrop/
# BookLore auto-imports and fetches metadata from Goodreads, Google Books, etc.
# Multi-user support: create accounts via the web UI
