# FreshRSS — Self-Hosted RSS Reader on VM
# A lightweight, self-hostable RSS feed aggregator
# Access: http://vm/freshrss (via Traefik)
# Ref: https://freshrss.org | https://hub.docker.com/r/freshrss/freshrss
#
# Crane images needed:
#   crane pull freshrss/freshrss:latest /tmp/freshrss.tar
#   crane pull postgres:16-alpine /tmp/postgres-16-alpine.tar
#
# Volume setup:
#   mkdir -p ~/docker/freshrss/{data,extensions,db}
#
# Traefik: create ~/traefik/dynamic/freshrss.yml (see SKILL.md template)
# Homepage: add entry under appropriate group in ~/homepage/config/services.yaml

services:
  freshrss:
    image: freshrss/freshrss:latest
    restart: unless-stopped
    # No host ports — Traefik routes /freshrss via traefik-proxy network
    volumes:
      - /home/htlin222/docker/freshrss/data:/var/www/FreshRSS/data
      - /home/htlin222/docker/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: Asia/Taipei
      CRON_MIN: "3,33"              # Auto-fetch feeds at :03 and :33
      FRESHRSS_ENV: production
      FRESHRSS_INSTALL: |-
        --api_enabled
        --db-type pgsql
        --db-host db
        --db-port 5432
        --db-base freshrss
        --db-user freshrss
        --db-password changeme
    depends_on:
      db:
        condition: service_healthy
    networks:
      - traefik-proxy

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - /home/htlin222/docker/freshrss/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: freshrss
      POSTGRES_USER: freshrss
      POSTGRES_PASSWORD: changeme
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U freshrss"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - traefik-proxy

networks:
  traefik-proxy:
    external: true

# First run: visit http://vm/freshrss to complete setup wizard
# Mobile: use FeedMe (Android) or NetNewsWire (iOS) with FreshRSS API
