-- ~/.config/nvim/lua/custom/configs/*.lua
local plug_list = {
	--- First to load
	"lspsaga", -- https://github.com/nvimdev/lspsaga.nvim
	"carbon-now",
	"lsp-timeout",
	"fugitive", -- "tpope/vim-fugitive",
	"neoclip",
	"hawtkeys",
	"automkdir",
	-- "papis",
	"r",
	-- "notator",
	"vim-markdown-toc",
	-- "inline-fold",
	"close-buffers",
	"gitlinker",
	"gitsigns",
	"octo",
	"fidget",
	"spider",
	-- 2023-12-26: added
	"marks",
	"urlview",
	"better-escape",
	"rainbow-delimiters",
	"pangu",
	"neocomposer",
	"trailblazer",
	"oil",
	-- "dressing",
	"conform",
	"lint",
	"mason-lspconfig",
	"firenvim",
	"nvim-lspconfig",
	"mason-nvim-dap", -- TODO: figure out how to use it
	-- "mason-tool-installer", -- WARN: Cause Error
	"nvim-treesitter-textobjects",
	"nvim-tree",
	-- telescope stuff
	"telekasten", -- ft.
	"telescope",
	"telescope-bibtex",
	"telescope-symbols",
	"compiler",
	"hbac",
	--- others
	"cursorline",
	"inc-rename",
	"modicator",
	"dial",
	"specs",
	"hover",
	"chatgpt",
	"trailblazer",
	"pick",
	"aerial",
	"cheatsheet",
	"harpoon",
	"aidoc",
	"hop", -- may replaced by
	"flash",
	-- "satellite", -- only support 0.10 now at 0.09
	-- "neoscroll",
	"winshift",
	-- "nvim-ufo",
	"mini",
	"neodev",
	"yanky",
	-- "vim-table-mode",
	-- "barbecue",
	"iswap",
	"fsread",
	"headlines",
	"legendary",
	"mkdnflow",
	"regexplainer",
	"neo-tree",
	"neotest",
	"noice", -- when suggestion show up, <C-y> to sent the command
	"nvim-dap",
	-- "markmap",
	"nvim-dap-python",
	"nvim-dap-ui",
	-- "nvim-search-and-replace",
	"nvim-surround",
	"pantran",
	"indent-blankline",
	"pretty-fold",
	"project",
	"scrollbar",
	"early-retirement",
	"due",
	"ufo",
	"quicknote",
	"search-replace",
	"symbols-outline",
	"trouble",
	"twilight",
	"mode",
	"vim-illuminate",
	-- "vim-startuptime",
	"todo-comments",
	"vim-tmux-navigator",
	"highlight-undo",
	"zen-mode",
	"gist",
	"cybu",
	-- "zk",
	"markdown-preview",
	"deadcolumn",
	"LuaSnip",
	"cmp",
	"numbertoggle",
	-- "filetype", -- not yet to figure out how does it works
	"neorg", -- TODO: 感覺很厲害的筆記系統，但我還沒想好要怎麼用
}
-- make the complete list
local plugins = {}
for _, plug in ipairs(plug_list) do
	plugins[#plugins + 1] = require("custom.configs." .. plug)
end
return plugins
